import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {PGlite} from '@electric-sql/pglite'
test('Postgres enforces review visibility, immutable objects and administrator transitions',async()=>{
 const db=new PGlite()
 const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',admin='33333333-3333-4333-8333-333333333333',id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
 try{
 await db.exec(`create role authenticated; create role anon; create schema auth; create schema storage;
 create table auth.users(id uuid primary key); insert into auth.users values ('${owner}'),('${other}'),('${admin}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 grant usage on schema auth,public,storage to authenticated,anon;
 create table public.harness_analytics_admins(user_id uuid primary key references auth.users);alter table public.harness_analytics_admins enable row level security;
 insert into public.harness_analytics_admins values('${admin}');
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id bigint generated always as identity,bucket_id text,name text);alter table storage.objects enable row level security;
 grant select,insert,update,delete on storage.objects to authenticated;`)
 await db.exec(await readFile(new URL('../migrations/001_market.sql',import.meta.url),'utf8'))
 await db.exec(await readFile(new URL('../migrations/002_ratings.sql',import.meta.url),'utf8'))
 await db.exec(await readFile(new URL('../migrations/003_package_icons.sql',import.meta.url),'utf8'))
 const as=async uid=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${uid}',false);set role authenticated;`)
 await as(owner)
 await db.exec(`insert into public.market_packages(id,name,author,description,platforms,version,harness_range,sha256,size_bytes) values('${id}','Demo','Author','A complete package description',array['Web'],'1.0.0','>=0.2.0','${'a'.repeat(64)}',10)`)
 await assert.rejects(db.exec(`select public.market_submit('${id}')`),/missing/)
 await db.exec(`insert into storage.objects(bucket_id,name) values('market-packages','${owner}/${id}.zip')`)
 await db.exec(`select public.market_submit('${id}')`)
 await as(other)
 assert.equal((await db.query('select * from public.market_packages')).rows.length,0)
 assert.equal((await db.query('select * from storage.objects')).rows.length,0)
 await assert.rejects(db.exec(`select public.market_review('${id}','approved','')`),/Administrator/)
 await as(owner)
 await assert.rejects(db.exec(`update public.market_packages set status='approved' where id='${id}'`),/permission denied/)
 assert.equal((await db.query(`update storage.objects set name='changed' returning *`)).rows.length,0)
 assert.equal((await db.query(`delete from storage.objects returning *`)).rows.length,0)
 await as(admin)
 assert.equal((await db.query('select * from public.market_packages')).rows.length,1)
 assert.equal((await db.query('select * from storage.objects')).rows.length,1)
 await db.exec(`select public.market_review('${id}','approved','Reviewed')`)
 await assert.rejects(db.exec(`select public.market_review('${id}','approved','again')`),/Status changed/)
 await as(other)
 assert.equal((await db.query('select * from public.market_packages')).rows.length,1)
 assert.equal((await db.query('select * from storage.objects')).rows.length,1)
 await db.exec(`select public.market_rate('${id}',5,'Reader','Useful package')`)
 await db.exec(`select public.market_rate('${id}',4,'Reader','Updated review')`)
 assert.equal((await db.query('select * from public.market_ratings')).rows.length,1)
 assert.equal(Number((await db.query(`select * from public.market_rating_summary(array['${id}']::uuid[])`)).rows[0].average),4)
 await assert.rejects(db.exec(`select public.market_rate('${id}',6,'Reader','bad')`),/Invalid rating/)
 await assert.rejects(db.exec(`select public.market_moderate_rating('${id}','${other}',true,'hide')`),/Administrator/)
 await as(owner)
 await assert.rejects(db.exec(`select public.market_rate('${id}',5,'Author','self')`),/other developers/)
 await as(admin)
 await db.exec(`select public.market_moderate_rating('${id}','${other}',true,'Inappropriate content')`)
 await as(owner)
 assert.equal((await db.query('select * from public.market_ratings')).rows.length,0)
 await as(other)
 await db.exec(`select public.market_rate('${id}',5,'Reader','Edited hidden review')`)
 assert.equal((await db.query('select * from public.market_ratings')).rows[0].hidden,true)
 assert.equal((await db.query(`select * from public.market_rating_summary(array['${id}']::uuid[])`)).rows.length,0)
 await db.exec(`select public.market_remove_rating('${id}')`)
 await db.exec(`select public.market_rate('${id}',3,'Reader','Restored by reviewer')`)
 assert.equal((await db.query('select * from public.market_ratings')).rows[0].hidden,true)
 await as(admin)
 await db.exec(`select public.market_moderate_rating('${id}','${other}',false,'Reviewed revision')`)
 assert.equal(Number((await db.query(`select * from public.market_rating_summary(array['${id}']::uuid[])`)).rows[0].average),3)
 await as(other)
 await db.exec(`select set_config('request.jwt.claims','{"is_anonymous":true}',false)`)
 await assert.rejects(db.exec(`select public.market_rate('${id}',5,'Guest','no')`),/Verified account/)
 await db.exec(`select set_config('request.jwt.claims','{}',false)`)
 await as(admin)
 await assert.rejects(db.exec(`select public.market_review('${id}','withdrawn','')`),/reason required/)
 await db.exec(`select public.market_review('${id}','withdrawn','Compatibility issue')`)
 await as(other)
 assert.equal((await db.query('select * from public.market_packages')).rows.length,0)
 assert.equal((await db.query('select * from storage.objects')).rows.length,0)
 await db.exec(`select set_config('request.jwt.claims','{"is_anonymous":true}',false)`)
 await assert.rejects(db.exec(`insert into public.market_packages(id,name,author,description,platforms,version,harness_range,sha256,size_bytes) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Demo','Author','A complete package description',array['Web'],'1.0.0','>=0.2.0','${'a'.repeat(64)}',10)`),/row-level security/)
 await db.exec("reset role;select set_config('request.jwt.claims','{}',false)")
 await db.exec(await readFile(new URL('../migrations/004_lifecycle.sql',import.meta.url),'utf8'))
 await db.exec(await readFile(new URL('../migrations/005_version_reviews.sql',import.meta.url),'utf8'))
 await as(owner)
 const metadata={name:'Lifecycle',author:'Author',description:'A complete lifecycle package',platforms:['Web'],version:'1.0.0',harness_range:'>=0.2.0'}
 const begin=async(version,digest='b')=>(await db.query('select (public.market_begin_release($1::jsonb,$2,$3,10)).*',[JSON.stringify({...metadata,version}),'lifecycle',digest.repeat(64)])).rows[0]
 const first=await begin('1.0.0')
 assert.equal((await begin('1.0.0')).id,first.id)
 await assert.rejects(begin('1.0.0','c'),/increment/)
 await db.exec(`insert into storage.objects(bucket_id,name) values('market-packages','${owner}/${first.id}.zip');select public.market_submit('${first.id}')`)
 await as(other)
 await assert.rejects(db.exec(`select public.market_owner_action('${first.id}','cancel','no')`),/owned/)
 await as(admin)
 await db.exec(`select public.market_review('${first.id}','approved','OK')`)
 await as(other)
 await db.exec(`select public.market_rate('${first.id}',5,'Reader','First version')`)
 assert.equal((await db.query('select * from market_scripts')).rows.length,1)
 await as(owner)
 const next=await begin('2.0.0','c')
 await db.exec(`insert into storage.objects(bucket_id,name) values('market-packages','${owner}/${next.id}.zip');select public.market_submit('${next.id}')`)
 await as(other)
 assert.equal((await db.query("select version from market_packages where adapter_id='lifecycle' and status='approved'")).rows[0].version,'1.0.0')
 await as(owner)
 await db.exec(`select public.market_owner_action('${next.id}','cancel','Revise');select public.market_submit('${next.id}')`)
 await as(admin)
 await db.exec(`select public.market_review('${next.id}','approved','OK')`)
 await as(other)
 assert.deepEqual((await db.query("select version from market_packages where adapter_id='lifecycle' and status='approved'")).rows.map(r=>r.version),['2.0.0'])
 await db.exec(`select public.market_rate('${next.id}',4,'Reader','New version')`)
 const summary=(await db.query(`select * from market_rating_summary(array['${next.id}']::uuid[])`)).rows[0]
 assert.equal(Number(summary.total),1);assert.equal(Number(summary.average),4)
 assert.equal((await db.query(`select * from market_ratings where package_id in ('${first.id}','${next.id}')`)).rows.length,2)
 await as(owner)
 assert.equal((await db.query(`select status from market_packages where id='${first.id}'`)).rows[0].status,'superseded')
 await db.exec(`select public.market_owner_action('${next.id}','unlist','Maintenance');select public.market_submit('${next.id}')`)
 await as(admin)
 await db.exec(`select public.market_review('${next.id}','approved','Relisted')`)
 await db.exec(`select public.market_review('${next.id}','withdrawn','Fix required')`)
 await as(owner)
 await assert.rejects(db.exec(`select public.market_submit('${next.id}')`),/Administrator withdrew/)
 assert.ok((await db.query(`select * from market_events where package_id='${next.id}'`)).rows.length>=8)
 const old=await begin('1.5.0','d')
 await db.exec(`insert into storage.objects(bucket_id,name) values('market-packages','${owner}/${old.id}.zip');select public.market_submit('${old.id}')`)
 await as(admin)
 await assert.rejects(db.exec(`select public.market_review('${old.id}','approved','Old')`),/newer/)
 }finally{await db.close()}
})
