const assert = require('node:assert/strict')
const fs = require('node:fs')
const test = require('node:test')

const workbench = fs.readFileSync('app/src/renderer/views/AiImageWorkbench.vue', 'utf8')
const promptPicker = fs.readFileSync('app/src/renderer/components/PromptLibraryPickerModal.vue', 'utf8')

function functionBody(source, name, nextName) {
  const start = source.indexOf(`function ${name}`)
  const end = source.indexOf(`function ${nextName}`, start + 1)
  assert.ok(start >= 0, `${name} missing`)
  assert.ok(end > start, `${nextName} missing after ${name}`)
  return source.slice(start, end)
}

test('advanced JSON validates inline and blocks single or batch submission instead of silently dropping input', () => {
  assert.match(workbench, /import \{ parseAdvancedJsonConfig \} from '\.\.\/utils\/aiImageAdvancedJson\.mjs'/)
  assert.match(workbench, /const advancedJsonError = computed/)
  assert.match(workbench, /:aria-invalid="advancedJsonError \? 'true' : 'false'"/)
  assert.match(workbench, /aria-describedby="aiw-advanced-json-error"/)
  assert.match(workbench, /id="aiw-advanced-json-error"[\s\S]*role="alert"/)
  assert.match(workbench, /watch\(advancedJsonError, \(error, previousError\) => \{[\s\S]*if \(!error && previousError && errorMessage\.value === previousError\) errorMessage\.value = ''/)
  assert.match(functionBody(workbench, 'generate', 'normalizeGenerateError'), /assertAdvancedJsonValid\(\)/)
  assert.match(functionBody(workbench, 'submitBatchGeneration', 'generate'), /assertAdvancedJsonValid\(\)/)
  assert.doesNotMatch(functionBody(workbench, 'generate', 'normalizeGenerateError'), /silentAdvanced:\s*true/)
})

test('failed queue cards expose retry context and preserve operator recovery actions', () => {
  assert.match(workbench, /retrySummaryText/)
  assert.match(workbench, /generationFailureMessage/)
  assert.match(workbench, /retryFailedRun\(item\)/)
  assert.match(workbench, /copyFailedPrompt\(item\)/)
  assert.match(workbench, /restoreFailedRunInputs\(item\)/)
  assert.match(workbench, /重试本队列/)
  assert.match(workbench, /复制 Prompt/)
  assert.match(workbench, /打开参数/)
  assert.match(functionBody(workbench, 'retryFailedRun', 'copyFailedPrompt'), /window\.cs\.retryAiImageRun\(jobUid, runUid\)/)
  assert.match(functionBody(workbench, 'retryFailedRun', 'copyFailedPrompt'), /startJobPolling\(jobUid\)/)
})

test('stale generation errors clear on input changes and task cards surface failed run reasons', () => {
  const clearBody = functionBody(workbench, 'clearGenerateError', 'buildJobPayload')
  const chooseMainBody = functionBody(workbench, 'chooseMainImage', 'chooseReferenceImages')
  const chooseReferenceBody = functionBody(workbench, 'chooseReferenceImages', 'chooseOutputFolder')
  const chooseOutputBody = functionBody(workbench, 'chooseOutputFolder', 'chooseDirectory')
  const taskResultBody = functionBody(workbench, 'taskResultLine', 'taskPreviewItems')
  const taskPreviewBody = functionBody(workbench, 'taskPreviewItems', 'queueMetaLine')

  assert.match(workbench, /form\.modelId[\s\S]*form\.referenceImagePaths\.join\('\\n'\)[\s\S]*clearGenerateError\(\)/)
  assert.match(clearBody, /if \(errorMessage\.value\) errorMessage\.value = ''/)
  assert.match(clearBody, /if \(batchGenerationDialog\.error\) batchGenerationDialog\.error = ''/)
  assert.match(chooseMainBody, /importInputSelection\('main'/)
  assert.match(chooseReferenceBody, /importInputSelection\('reference'/)
  assert.match(workbench, /Object\.assign\(state, mergeImageInputs[\s\S]*else clearGenerateError\(\)/)
  assert.match(chooseOutputBody, /clearGenerateError\(\)[\s\S]*form\.output_dir = directory/)
  assert.match(workbench, /function latestTaskFailure/)
  assert.match(workbench, /function compactTaskFailureText/)
  assert.match(taskResultBody, /collectResultCards\(job\)\.length/)
  assert.match(taskResultBody, /latestTaskFailure\(job\)/)
  assert.match(taskResultBody, /compactTaskFailureText\(failure\)/)
  assert.match(taskPreviewBody, /collectResultCards\(job\)\.slice\(0, 4\)/)
  assert.match(workbench, /<small :title="taskResultLine\(job\)">\{\{ taskResultLine\(job\) \}\}<\/small>/)
})

test('Prompt library converts infrastructure failures into operator-facing recovery copy', () => {
  assert.match(promptPicker, /import \{ promptLibraryFailureMessage \} from '\.\.\/utils\/aiImageOperatorMessages\.mjs'/)
  assert.match(promptPicker, /const operatorError = computed/)
  assert.match(promptPicker, /role="alert"/)
  assert.match(promptPicker, /刷新重试/)
  assert.match(promptPicker, /operatorError/)
})
