import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

function read(path) {
  return fs.readFileSync(path, 'utf8')
}

test('App registers AI image route after task center and before data files', () => {
  const app = read('app/src/renderer/App.vue')
  const taskCenter = app.indexOf("id: 'task_center'")
  const aiImage = app.indexOf("id: 'ai_image'")
  const files = app.indexOf("id: 'files'")

  assert.notEqual(taskCenter, -1, 'task center route is missing')
  assert.notEqual(aiImage, -1, 'AI image route is missing')
  assert.notEqual(files, -1, 'data files route is missing')
  assert.ok(taskCenter < aiImage, 'AI image route should follow task center')
  assert.ok(aiImage < files, 'AI image route should precede data files')
  assert.match(app, /label: 'AI 生图'/)
  assert.match(app, /<KeepAlive>[\s\S]*<AiImageWorkbench[\s\S]*v-if="currentView === 'ai_image'"[\s\S]*@open-settings="openSettingsPanel\('ai-1xm'\)"[\s\S]*<\/KeepAlive>/)
  assert.doesNotMatch(app, /<AiImageWorkbench[\s\S]*v-show=/)
})

test('App keeps the global sidebar visible on the AI image page', () => {
  const app = read('app/src/renderer/App.vue')

  assert.doesNotMatch(app, /v-if="currentView !== 'ai_image'"[\s\S]*class="sidebar"/)
  assert.doesNotMatch(app, /layout-focus/)
  assert.doesNotMatch(app, /content-focus/)
  assert.match(app, /<aside class="sidebar">/)
})

test('Settings page accepts focus panel id and exposes 1XM image model keys', () => {
  const settings = read('app/src/renderer/views/SettingsPage.vue')

  assert.match(settings, /focusPanelId/)
  assert.match(settings, /watch\(\(\) => props\.focusPanelId/)
  assert.match(settings, /1XM 图片模型/)
  assert.doesNotMatch(settings, /1XM GPT-Image-2/)
  assert.match(settings, /ai\.1xm\.gemini_3_1_flash_image_preview_key/)
  assert.match(settings, /ai\.1xm\.gemini_3_pro_image_preview_key/)
  assert.match(settings, /Gemini 3\.1 Flash Image Preview Key/)
  assert.match(settings, /Gemini 3 Pro Image Preview Key/)
})

test('Settings page marks the AI menu configured when any image-model key is present', () => {
  const settings = read('app/src/renderer/views/SettingsPage.vue')

  assert.match(settings, /statusKeys: ai1xmKeyFields/)
  assert.match(settings, /isMenuChildConfigured\(child\)/)
  assert.match(settings, /hasAnyFieldConfigured\(child\.statusKeys\)/)
})

test('AI image workbench renders option 3 shell regions and settings action', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /class="aiw-workbench aiw-option-3"/)
  assert.doesNotMatch(workbench, /class="aiw-param-ribbon"/)
  assert.match(workbench, /class="aiw-prompt-panel aiw-task-panel"/)
  assert.match(workbench, /class="aiw-results-grid"/)
  assert.match(workbench, /:aria-busy="generating \? 'true' : 'false'"/)
  assert.match(workbench, /class="aiw-workspace-body"/)
  assert.match(workbench, /class="aiw-history-sidebar"/)
  assert.doesNotMatch(workbench, /class="aiw-generate-footer"/)
  assert.match(workbench, /AI 生图工作台/)
  assert.match(workbench, /支持主图、参考图、Prompt、比例尺寸联动和多模型生成/)
  assert.match(workbench, /outputDirHint\(\)/)
  assert.match(workbench, /点击上传主图/)
  assert.match(workbench, /点击添加参考图/)
  assert.match(workbench, /选择文件夹/)
  assert.match(workbench, /<AiwIcon name="settings" \/>配置/)
  assert.doesNotMatch(workbench, /配置模型 Key/)
  assert.doesNotMatch(workbench, /本地 1XM 图片模型工作台/)
  assert.doesNotMatch(workbench, /去设置 1XM Key/)
  assert.doesNotMatch(workbench, /提交 1XM 任务/)
  assert.match(workbench, /defineEmits\(\['open-settings'\]\)/)
})

test('cached AI image workbench reloads model keys after returning from settings', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /onActivated/)
  assert.match(workbench, /onActivated\(\(\) => \{\s*void loadSettings\(\)\s*\}\)/)
})

test('AI image workbench uses picker interactions and hides canvas entry for now', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /const taskSidebarOpen = ref\(true\)/)
  assert.match(workbench, /STORAGE_KEY = 'crawshrimp\.aiImageWorkbench\.state\.v2'/)
  assert.match(workbench, /restorePersistedWorkbench/)
  assert.match(workbench, /persistWorkbenchState/)
  assert.match(workbench, /scheduleTaskAutosave/)
  assert.match(workbench, /window\.cs\.updateAiImageJob/)
  assert.match(workbench, /createNewTask/)
  assert.match(workbench, /taskRecords/)
  assert.match(workbench, /任务记录/)
  assert.match(workbench, /新建任务/)
  assert.match(workbench, /window\.cs\.browseFile\(opts\)/)
  assert.match(workbench, /chooseMainImage/)
  assert.match(workbench, /chooseReferenceImages/)
  assert.match(workbench, /chooseOutputFolder/)
  assert.match(workbench, /readLocalImagePreview/)
  assert.match(workbench, /imagePreviewSrc\(form\.mainImagePath\)/)
  assert.match(workbench, /aiw-preview-fallback/)
  assert.match(workbench, /visibleResultCards/)
  assert.match(workbench, /aiw-loading-preview/)
  assert.match(workbench, /aiw-wave-flow/)
  assert.match(workbench, /aiw-loading-breathe/)
  assert.doesNotMatch(workbench, /aiw-shimmer/)
  assert.match(workbench, /class="aiw-history-item"/)
  assert.match(workbench, /button:focus-visible/)
  assert.match(workbench, /summary\.image_urls/)
  const generateStart = workbench.indexOf('async function generate()')
  const generateEnd = workbench.indexOf('function normalizeGenerateError', generateStart)
  const generateBody = workbench.slice(generateStart, generateEnd)
  assert.doesNotMatch(generateBody, /currentJob\.value = null/)
  assert.match(workbench, /main_image_path: form\.mainImagePath/)
  assert.match(workbench, /reference_image_paths: \[\.\.\.form\.referenceImagePaths\]/)
  assert.match(workbench, /return item\?\.url \|\| item\?\.path \|\| ''/)
  assert.match(workbench, /本地 AI 生图服务未就绪，请重启抓虾客户端后再试/)
  assert.match(workbench, /runResult && runResult\.ok === false/)
  assert.match(workbench, /runResult\.summary\?\.error/)
  assert.doesNotMatch(workbench, />画布</)
  assert.doesNotMatch(workbench, /sendToCanvas/)
  assert.doesNotMatch(workbench, /createCanvasDocument/)
})

test('AI image task records show latest generation time without mixed settings metadata', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const sidebarStart = workbench.indexOf('class="aiw-history-sidebar"')
  const sidebarEnd = workbench.indexOf('</aside>', sidebarStart)
  const sidebarBody = workbench.slice(sidebarStart, sidebarEnd)
  const latestStart = workbench.indexOf('function latestTaskGenerationAt')
  const metaStart = workbench.indexOf('function taskMetaLine')
  const metaEnd = workbench.indexOf('function taskResultLine', metaStart)
  const latestBody = workbench.slice(latestStart, metaStart)
  const metaBody = workbench.slice(metaStart, metaEnd)

  assert.match(sidebarBody, /<span>\{\{ taskMetaLine\(job\) \}\}<\/span>/)
  assert.match(sidebarBody, /<small>\{\{ taskResultLine\(job\) \}\}<\/small>/)
  assert.notEqual(latestStart, -1, 'latestTaskGenerationAt should exist')
  assert.match(latestBody, /summary\.runs/)
  assert.match(latestBody, /created_at/)
  assert.match(latestBody, /collectResultCards\(job\)\.length/)
  assert.match(metaBody, /latestTaskGenerationAt\(job\)/)
  assert.match(metaBody, /最近生成/)
  assert.match(metaBody, /尚未生成/)
  assert.doesNotMatch(metaBody, /model_key|params\.size|params\.ratio|params\.n|job\.status|张/)
})

test('AI image workbench clears submitted prompt and input images after generation starts', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const generateStart = workbench.indexOf('async function generate()')
  const generateEnd = workbench.indexOf('function normalizeGenerateError', generateStart)
  const generateBody = workbench.slice(generateStart, generateEnd)
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function removeReferencePath', editStart)
  const editBody = workbench.slice(editStart, editEnd)
  const helperStart = workbench.indexOf('function clearSubmittedTaskInputs')
  const helperEnd = workbench.indexOf('async function generate()', helperStart)
  const helperBody = workbench.slice(helperStart, helperEnd)
  const restoreStart = workbench.indexOf('async function restoreJob(job, options = {})')
  const restoreEnd = workbench.indexOf('function toggleTaskSidebar', restoreStart)
  const restoreBody = workbench.slice(restoreStart, restoreEnd)

  assert.notEqual(helperStart, -1, 'submitted-input clearing helper should exist')
  assert.match(helperBody, /prompt: ''/)
  assert.match(helperBody, /mainImagePath: ''/)
  assert.match(helperBody, /referenceImagePaths: \[\]/)
  assert.match(helperBody, /submittedInputsCleared: true/)
  assert.match(generateBody, /clearSubmittedTaskInputs\(submittedSnapshot, jobUid\)/)
  assert.ok(
    generateBody.indexOf('clearSubmittedTaskInputs(submittedSnapshot, jobUid)') < generateBody.indexOf('await window.cs.runAiImageJob(jobUid)'),
    'the submitted form inputs should clear as soon as the generation task is accepted',
  )
  assert.match(editBody, /let submittedInputsCleared = false/)
  assert.match(editBody, /submittedInputsCleared = true/)
  assert.match(editBody, /clearSubmittedTaskInputs\(snapshot, jobUid\)/)
  assert.ok(
    editBody.indexOf('clearSubmittedTaskInputs(snapshot, jobUid)') < editBody.indexOf('await window.cs.runAiImageJob(jobUid)'),
    'lightbox edit inputs should clear as soon as the edit task is accepted',
  )
  assert.match(helperBody, /targetJobUid && targetJobUid !== activeJobUid\.value/)
  assert.match(helperBody, /taskDrafts\[targetJobUid\]/)
  assert.match(restoreBody, /const submittedInputsCleared = Boolean/)
  assert.match(restoreBody, /!submittedInputsCleared[\s\S]*mainAsset/)
  assert.match(restoreBody, /!submittedInputsCleared[\s\S]*asset\.kind === 'reference'/)
})

test('AI image workbench offers batch generation with shared prompt library picking', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const promptPicker = read('app/src/renderer/components/PromptLibraryPickerModal.vue')
  const tmallDrawer = read('app/src/renderer/views/TmallAiApprovalDrawer.vue')
  const openStart = workbench.indexOf('function openBatchGenerationDialog')
  const submitStart = workbench.indexOf('async function submitBatchGeneration')
  const submitEnd = workbench.indexOf('function normalizeGenerateError', submitStart)
  const submitBody = workbench.slice(submitStart, submitEnd)
  const payloadStart = workbench.indexOf('function buildBatchJobPayload')
  const payloadEnd = workbench.indexOf('function scheduleTaskAutosave', payloadStart)
  const payloadBody = workbench.slice(payloadStart, payloadEnd)

  assert.match(workbench, /import PromptLibraryPickerModal from '\.\.\/components\/PromptLibraryPickerModal\.vue'/)
  assert.match(tmallDrawer, /import PromptLibraryPickerModal from '\.\.\/components\/PromptLibraryPickerModal\.vue'/)
  assert.match(workbench, /@click="openBatchGenerationDialog"/)
  assert.match(workbench, />批量生成</)
  assert.match(workbench, /class="aiw-batch-dialog"/)
  assert.match(workbench, /aria-label="批量生成"/)
  assert.match(workbench, /class="aiw-batch-board"/)
  assert.match(workbench, /class="aiw-batch-source-column"/)
  assert.match(workbench, /class="aiw-batch-prompt-board"/)
  assert.match(workbench, /v-for="\(card, index\) in batchPromptCards"/)
  assert.match(workbench, /openBatchPromptLibraryPicker\(card\)/)
  assert.match(workbench, /:disabled="batchGenerationDialog\.submitting" @click="chooseBatchMainImage"/)
  assert.match(workbench, /:disabled="batchGenerationDialog\.submitting" @click="chooseBatchReferenceImages"/)
  assert.match(workbench, /:disabled="batchGenerationDialog\.submitting \|\| batchPromptCards\.length >= MAX_BATCH_PROMPTS" @click="addBatchPromptCard"/)
  assert.match(workbench, /:disabled="batchGenerationDialog\.submitting \|\| batchPromptCards\.length <= 1"/)
  assert.match(workbench, /@media \(max-width: 1060px\)[\s\S]*\.aiw-batch-board/)
  assert.match(workbench, /<PromptLibraryPickerModal/)
  assert.match(tmallDrawer, /<PromptLibraryPickerModal/)
  assert.match(promptPicker, /buildPromptLibraryPickerLibraries/)
  assert.match(promptPicker, /window\.cs\.listLocalPromptLibraries/)
  assert.match(promptPicker, /window\.cs\.listCloudPromptLibraries/)
  assert.match(promptPicker, /templates\.value = \(selectedLibrary\.templates \|\| \[\]\)/)
  assert.match(promptPicker, /createPromptLibraryRequestGuard/)
  assert.match(promptPicker, /promptLibraryRequestGuard\.begin\(id\)/)
  assert.match(promptPicker, /promptLibraryRequestGuard\.isCurrent\(requestToken, id\)/)
  assert.match(promptPicker, /promptLibraryRequestGuard\.invalidate\(\)/)
  assert.match(promptPicker, /emit\('select',/)
  assert.match(workbench, /const batchGenerationDialog = reactive/)
  assert.match(workbench, /const batchPromptCards = computed/)
  assert.match(openStart === -1 ? '' : workbench.slice(openStart, submitStart), /createBatchPromptCard/)
  assert.match(payloadBody, /const requestedCount = normalizeBatchPromptCount\(card\.count, \{ forceSingle: isNanoBananaModel\(model\.id\) \}\)/)
  assert.match(payloadBody, /n: requestedCount/)
  assert.match(payloadBody, /params\.n = requestedCount/)
  assert.match(submitBody, /const promptCards = batchPromptCards\.value/)
  assert.match(submitBody, /const activeTask = await ensureCurrentTask\(\)/)
  assert.match(submitBody, /window\.cs\.updateAiImageJob\(jobUid, sharedPayload\)/)
  assert.match(submitBody, /window\.cs\.batchRunAiImageJob\(jobUid,/)
  assert.match(submitBody, /count: normalizeBatchPromptCount\(card\.count, \{ forceSingle: batchNanoBanana\.value \}\)/)
  assert.match(submitBody, /if \(!batchResult\?\.accepted\)/)
  assert.match(submitBody, /clearSubmittedTaskInputs\(snapshot, jobUid\)/)
  assert.match(submitBody, /if \(hasActiveRuns\(currentJob\.value\)\) startJobPolling\(jobUid\)/)
})

test('AI image workbench lets single generation reuse the shared Prompt picker', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /@click="openSinglePromptLibraryPicker"/)
  assert.match(workbench, /aria-label="从 Prompt 库选择" title="从 Prompt 库选择"/)
  assert.match(workbench, /<AiwIcon name="text" \/>Prompt 库/)
  assert.match(workbench, /function openSinglePromptLibraryPicker\(\)/)
  assert.match(workbench, /batchPromptLibraryPicker\.target = 'single'/)
  assert.match(workbench, /batchPromptLibraryPicker\.target = 'batch'/)
  assert.match(workbench, /function selectPromptLibraryTemplate\(template\)/)
  assert.match(workbench, /if \(batchPromptLibraryPicker\.target === 'single'\)[\s\S]*form\.prompt = promptText/)
  assert.match(workbench, /@select="selectPromptLibraryTemplate"/)
})

test('AI image workbench only sends the current annotation during lightbox edits', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function removeReferencePath', editStart)
  const editBody = workbench.slice(editStart, editEnd)
  const helperStart = workbench.indexOf('function filterGeneratedAnnotationReferences')
  const helperEnd = workbench.indexOf('function clearSubmittedTaskInputs', helperStart)
  const helperBody = workbench.slice(helperStart, helperEnd)
  const applyStart = workbench.indexOf('function applyFormSnapshot')
  const applyEnd = workbench.indexOf('function isGeneratedAnnotationReferencePath', applyStart)
  const applyBody = workbench.slice(applyStart, applyEnd)
  const restoreStart = workbench.indexOf('async function restoreJob(job, options = {})')
  const restoreEnd = workbench.indexOf('function toggleTaskSidebar', restoreStart)
  const restoreBody = workbench.slice(restoreStart, restoreEnd)

  assert.match(workbench, /function isGeneratedAnnotationReferencePath\(path\)/)
  assert.match(workbench, /function filterGeneratedAnnotationReferences\(paths = \[\]\)/)
  assert.match(workbench, /\^annotation\(\?:-\|_\)/)
  assert.match(helperBody, /isGeneratedAnnotationReferencePath/)
  assert.match(applyBody, /referenceImagePaths: filterGeneratedAnnotationReferences\(snapshot\.referenceImagePaths\)/)
  assert.match(editBody, /const retainedSnapshotReferences = filterGeneratedAnnotationReferences\(snapshot\.referenceImagePaths\)/)
  assert.match(editBody, /\.\.\.retainedSnapshotReferences/)
  assert.doesNotMatch(editBody, /\.\.\.snapshot\.referenceImagePaths/)
  assert.match(editBody, /\.\.\.referencePaths/)
  assert.match(editBody, /annotationPath/)
  assert.match(restoreBody, /filterGeneratedAnnotationReferences\(formDetail\.params\.reference_image_paths\)/)
})

test('AI image workbench maps ratio to compatible size options', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /const sizeOptions = computed\(\(\) => sizeOptionsForModel\(form\.modelId, form\.ratio\)\)/)
  assert.match(workbench, /<select v-model="form\.ratio" @change="syncSizeFromRatio">/)
  assert.match(workbench, /<select v-model="form\.size" @change="syncRatioFromSize">/)
  assert.match(workbench, /form\.size = sizeForModel\(form\.modelId, form\.ratio, form\.size\)/)
  assert.match(workbench, /form\.ratio = ratioForSize\(form\.size, form\.ratio\)/)
})

test('AI image task records keep history order while highlighting the clicked task', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const taskRecordsStart = workbench.indexOf('const taskRecords = computed')
  const taskRecordsEnd = workbench.indexOf('onMounted', taskRecordsStart)
  const taskRecordsBody = workbench.slice(taskRecordsStart, taskRecordsEnd)
  const restoreStart = workbench.indexOf('async function restoreJob(job, options = {})')
  const restoreEnd = workbench.indexOf('function openOutputFolder', restoreStart)
  const restoreBody = workbench.slice(restoreStart, restoreEnd)

  assert.notEqual(taskRecordsStart, -1, 'taskRecords computed should exist')
  assert.ok(
    taskRecordsBody.indexOf('for (const job of jobs.value)') < taskRecordsBody.indexOf('if (currentJob.value?.job_uid && !seen.has(currentJob.value.job_uid) && !isAiVideoWorkflowJob(currentJob.value))'),
    'taskRecords should preserve jobs.value ordering before adding an unlisted current task',
  )
  assert.match(taskRecordsBody, /if \(!jobUid \|\| seen\.has\(jobUid\) \|\| isAiVideoWorkflowJob\(job\)\) continue/)
  assert.match(taskRecordsBody, /records\.unshift\(mergeJobWithDraft\(currentJob\.value, \{ includeGeneratedDrafts: false \}\)\)/)
  assert.match(workbench, /const pendingActiveJobUid = ref\(''\)/)
  assert.match(workbench, /const highlightedJobUid = computed\(\(\) => pendingActiveJobUid\.value \|\| activeJobUid\.value\)/)
  assert.match(workbench, /:class="\{ active: highlightedJobUid === job\.job_uid \}"/)
  assert.ok(
    restoreBody.indexOf('pendingActiveJobUid.value = job.job_uid') < restoreBody.indexOf('window.cs.getAiImageJob(job.job_uid)'),
    'clicked task should highlight before detail loading finishes',
  )
  assert.match(
    restoreBody,
    /currentJob\.value = detail\s*pendingActiveJobUid\.value = ''/,
    'pending highlight should clear immediately after the current task is restored',
  )
})

test('AI image workbench restores history from detail payload before setting current job', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const restoreStart = workbench.indexOf('async function restoreJob(job, options = {})')
  const restoreEnd = workbench.indexOf('function openOutputFolder', restoreStart)
  const restoreBody = workbench.slice(restoreStart, restoreEnd)

  assert.notEqual(restoreStart, -1, 'restoreJob should be async')
  assert.match(restoreBody, /window\.cs\.getAiImageJob\(job\.job_uid\)/)
  assert.ok(
    restoreBody.indexOf('window.cs.getAiImageJob(job.job_uid)') < restoreBody.indexOf('currentJob.value ='),
    'restoreJob should fetch detail before assigning currentJob',
  )
})

test('AI image workbench presents result queues, explicitly selectable results, task thumbnails, and lightbox preview', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /const resultQueues = computed\(\(\) => collectResultQueues\(currentJob\.value\)\)/)
  assert.match(workbench, /const visibleResultQueues = computed/)
  assert.match(workbench, /class="aiw-result-queue"/)
  assert.match(workbench, /queuePromptPreview\(queue\)/)
  assert.match(workbench, /openPromptDialog\(queue\)/)
  assert.match(workbench, /class="aiw-select-toggle"/)
  assert.match(workbench, /:aria-pressed="selectedResults\.has\(resultKey\(item\)\) \? 'true' : 'false'"/)
  assert.match(workbench, /@click\.stop="toggleResult\(item\)"/)
  assert.doesNotMatch(workbench, /class="aiw-result-card"[\s\S]{0,400}@click="toggleResult\(item\)"/)
  assert.doesNotMatch(workbench, /class="aiw-result-card"[\s\S]{0,400}role="button"/)
  assert.match(workbench, /@click\.stop="openLightbox\(item\)"/)
  assert.match(workbench, /selectAllVisibleResults/)
  assert.match(workbench, /allVisibleSelected/)
  assert.match(workbench, /class="aiw-history-thumbs"/)
  assert.match(workbench, /taskPreviewItems\(job\)/)
  assert.match(workbench, /const lightboxItem = ref\(null\)/)
  assert.match(workbench, /class="aiw-lightbox"/)
  assert.match(workbench, /function collectResultQueues\(job\)/)
  assert.match(workbench, /summary\.runs/)
})

test('AI image workbench opens a side-by-side lightbox edit panel from result cards', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const cardActionsStart = workbench.indexOf('class="aiw-result-card-actions"')
  const cardActionsEnd = workbench.indexOf('</div>', cardActionsStart)
  const cardActionsBody = workbench.slice(cardActionsStart, cardActionsEnd)
  const lightboxStart = workbench.indexOf('class="aiw-lightbox"')
  const lightboxEnd = workbench.indexOf('class="aiw-prompt-dialog"', lightboxStart)
  const lightboxBody = workbench.slice(lightboxStart, lightboxEnd)

  assert.match(cardActionsBody, /@click\.stop="openLightbox\(item, \{ mode: 'edit' \}\)"/)
  assert.match(cardActionsBody, />修改</)
  assert.match(workbench, /const lightboxEditPrompt = ref\(''\)/)
  assert.match(workbench, /const lightboxEditReferencePaths = ref\(\[\]\)/)
  assert.match(workbench, /const lightboxSourcePrompt = computed/)
  assert.match(workbench, /const lightboxPromptChain = computed/)
  assert.match(workbench, /function openLightbox\(item, options = \{\}\)/)
  assert.match(workbench, /function resetLightboxEditDraft\(item\)/)
  assert.match(workbench, /async function chooseLightboxEditReferences\(\)/)
  assert.match(workbench, /async function submitLightboxEdit\(\)/)
  assert.match(lightboxBody, /class="aiw-lightbox-layout"/)
  assert.match(lightboxBody, /class="aiw-lightbox-image-pane"/)
  assert.match(lightboxBody, /class="aiw-lightbox-edit-panel"/)
  assert.match(lightboxBody, /Prompt 修改链/)
  assert.match(lightboxBody, /v-for="entry in lightboxPromptChain"/)
  assert.match(workbench, /原图 Prompt/)
  assert.match(workbench, /修改 Prompt/)
  assert.match(lightboxBody, /新的修改提示词/)
  assert.match(lightboxBody, /上传参考图/)
  assert.match(lightboxBody, /进行下一步修改/)
})

test('AI image workbench constrains the lightbox to the viewport height', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const layoutStart = workbench.indexOf('.aiw-lightbox-layout {')
  const layoutEnd = workbench.indexOf('.aiw-lightbox-image-pane,', layoutStart)
  const layoutBody = workbench.slice(layoutStart, layoutEnd)
  const paneStart = workbench.indexOf('.aiw-lightbox-image-pane {')
  const paneEnd = workbench.indexOf('.aiw-lightbox figure {', paneStart)
  const paneBody = workbench.slice(paneStart, paneEnd)
  const figureStart = workbench.indexOf('.aiw-lightbox figure {')
  const figureEnd = workbench.indexOf('.aiw-lightbox-canvas,', figureStart)
  const figureBody = workbench.slice(figureStart, figureEnd)
  const canvasStart = workbench.indexOf('.aiw-lightbox-canvas {')
  const canvasEnd = workbench.indexOf('.aiw-lightbox-main-image {', canvasStart)
  const canvasBody = workbench.slice(canvasStart, canvasEnd)
  const imageStart = workbench.indexOf('.aiw-lightbox-main-image {')
  const imageEnd = workbench.indexOf('.aiw-lightbox-main-image.blurred', imageStart)
  const imageBody = workbench.slice(imageStart, imageEnd)

  assert.match(layoutBody, /height: calc\(100vh - 56px\)/)
  assert.match(layoutBody, /max-height: calc\(100vh - 56px\)/)
  assert.match(layoutBody, /overflow: hidden/)
  assert.match(paneBody, /min-width: 0/)
  assert.match(paneBody, /height: 100%/)
  assert.match(figureBody, /height: 100%/)
  assert.match(figureBody, /display: grid/)
  assert.match(figureBody, /grid-template-rows: minmax\(0, 1fr\) auto auto/)
  assert.match(figureBody, /overflow: hidden/)
  assert.doesNotMatch(canvasBody, /min-height: 520px/)
  assert.doesNotMatch(canvasBody, /max-height: calc\(92vh - 74px\)/)
  assert.match(imageBody, /max-height: 100%/)
  assert.doesNotMatch(imageBody, /max-height: calc\(92vh - 74px\)/)
})

test('AI image workbench keeps edit generations inside the lightbox with a one-image placeholder', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const submitStart = workbench.indexOf('async function submitLightboxEdit()')
  const submitEnd = workbench.indexOf('function removeReferencePath', submitStart)
  const submitBody = workbench.slice(submitStart, submitEnd)
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function applyLightboxEditResult', editStart)
  const editBody = workbench.slice(editStart, editEnd)
  const lightboxStart = workbench.indexOf('class="aiw-lightbox"')
  const lightboxEnd = workbench.indexOf('class="aiw-prompt-dialog"', lightboxStart)
  const lightboxBody = workbench.slice(lightboxStart, lightboxEnd)

  assert.match(workbench, /const lightboxEditResults = ref\(\[\]\)/)
  assert.match(workbench, /const lightboxEditSessionKey = ref\(''\)/)
  assert.match(workbench, /const lightboxEditResultsBySession = reactive\(new Map\(\)\)/)
  assert.match(workbench, /const lightboxEditOperations = shallowReactive\(new Map\(\)\)/)
  assert.match(workbench, /const lightboxEditSubmitting = computed\(\(\) => lightboxEditOperations\.has\(lightboxEditSessionKey\.value\)\)/)
  assert.match(workbench, /const lightboxEditBusy = computed\(\(\) => lightboxEditSubmitting\.value\)/)
  assert.match(workbench, /const lightboxEditActionLabel = computed/)
  assert.match(workbench, /const lightboxActiveIndex = ref\(0\)/)
  assert.match(workbench, /const lightboxPreviewItems = computed/)
  assert.match(workbench, /const lightboxActiveItem = computed/)
  assert.match(workbench, /class="aiw-lightbox-preview-strip"/)
  assert.match(lightboxBody, /v-for="\(item, index\) in lightboxPreviewItems"/)
  assert.match(lightboxBody, /@click="selectLightboxPreview\(index\)"/)
  assert.match(lightboxBody, /aiw-edit-spinner/)
  assert.match(lightboxBody, /v-if="lightboxActiveItem\?\.loading"/)
  assert.doesNotMatch(lightboxBody, /lightboxActiveItem\?\.loading \|\| lightboxEditSubmitting/)
  assert.match(lightboxBody, /:disabled="lightboxEditBusy"/)
  assert.match(lightboxBody, /:aria-busy="lightboxEditBusy \? 'true' : 'false'"/)
  assert.match(lightboxBody, /:class="\{ loading: lightboxEditBusy \}"/)
  assert.match(lightboxBody, /\{\{ lightboxEditActionLabel \}\}/)
  assert.match(submitBody, /lightboxEditOperations\.set\(sessionKey,/)
  assert.match(submitBody, /const referencePaths = \[\.\.\.lightboxEditReferencePaths\.value\]/)
  assert.match(submitBody, /appendLightboxEditPlaceholder\(sourceItem, nextPrompt, \{ activate: false \}\)/)
  assert.match(submitBody, /activateLightboxEditPlaceholder\(placeholder\)/)
  assert.ok(
    submitBody.indexOf('appendLightboxEditPlaceholder(sourceItem, nextPrompt, { activate: false })')
      < submitBody.indexOf('await requestLightboxAnnotationExport()'),
    'the loading placeholder should be created before annotation export begins',
  )
  assert.ok(
    submitBody.indexOf('await requestLightboxAnnotationExport()')
      < submitBody.indexOf('activateLightboxEditPlaceholder(placeholder)'),
    'annotation export should keep using the selected source image before switching to the loading placeholder',
  )
  assert.ok(
    submitBody.indexOf('activateLightboxEditPlaceholder(placeholder)')
      < submitBody.indexOf('const mainPath = await materializeResultForInput(sourceItem)'),
    'the loading placeholder should become active before source materialization begins',
  )
  assert.match(submitBody, /placeholder,/)
  assert.match(submitBody, /lightboxEditOperations\.delete\(sessionKey\)/)
  assert.doesNotMatch(submitBody, /lightboxEditSubmitting\.value = (?:true|false)/)
  assert.match(submitBody, /await runLightboxEditGeneration/)
  assert.match(submitBody, /referencePaths,\s*annotationDataUrl,/)
  assert.doesNotMatch(submitBody, /closeLightbox\(\)[\s\S]*await generate\(\)/)
  assert.notEqual(editStart, -1, 'runLightboxEditGeneration should exist')
  assert.match(workbench, /function removeLightboxEditPlaceholder\(placeholder\)/)
  assert.match(workbench, /function activateLightboxEditPlaceholder\(placeholder\)/)
  assert.match(workbench, /function appendLightboxEditPlaceholder\(sourceItem, prompt, options = \{\}\)/)
  assert.match(workbench, /function lightboxHistoryItems\(item\)/)
  assert.match(workbench, /function buildLightboxEditHistory\(sourceItem\)/)
  assert.match(workbench, /function buildLightboxPromptChain\(sourceItem, prompt\)/)
  assert.match(editBody, /const placeholder = existingPlaceholder \|\| appendLightboxEditPlaceholder\(sourceItem, prompt\)/)
  assert.match(editBody, /activateLightboxEditPlaceholder\(placeholder\)/)
  assert.match(editBody, /n: 1/)
  assert.match(editBody, /form\.count = 1/)
  assert.match(editBody, /window\.cs\.runAiImageJob\(jobUid\)/)
  assert.match(editBody, /applyLightboxEditResult\(placeholder, completedJob, runResult\?\.summary\?\.run_uid \|\| ''\)/)
})

test('AI image workbench keeps in-flight edits attached to their source lightbox session', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const resetStart = workbench.indexOf('function resetLightboxEditDraft')
  const resetEnd = workbench.indexOf('function openLightbox', resetStart)
  const resetBody = workbench.slice(resetStart, resetEnd)
  const closeStart = workbench.indexOf('function closeLightbox')
  const closeEnd = workbench.indexOf('function selectLightboxPreview', closeStart)
  const closeBody = workbench.slice(closeStart, closeEnd)
  const resolveStart = workbench.indexOf('function resolveLightboxAnnotationExportOnClose')
  const resolveEnd = workbench.indexOf('function captureLightboxAnnotation', resolveStart)
  const resolveBody = workbench.slice(resolveStart, resolveEnd)
  const appendStart = workbench.indexOf('function appendLightboxEditPlaceholder')
  const appendEnd = workbench.indexOf('function applyLightboxEditResult', appendStart)
  const appendBody = workbench.slice(appendStart, appendEnd)
  const applyStart = workbench.indexOf('function applyLightboxEditResult')
  const applyEnd = workbench.indexOf('async function runLightboxEditGeneration', applyStart)
  const applyBody = workbench.slice(applyStart, applyEnd)

  assert.match(workbench, /function lightboxEditResultsForSession\(sessionKey\)/)
  assert.match(resetBody, /lightboxEditSessionKey\.value = sessionKey/)
  assert.match(resetBody, /lightboxEditResults\.value = lightboxEditResultsForSession\(sessionKey\)/)
  assert.match(resetBody, /activateLightboxEditPlaceholder\(lastResult\)/)
  assert.match(closeBody, /resolveLightboxAnnotationExportOnClose\(\)/)
  assert.doesNotMatch(closeBody, /clearLightboxAnnotationExport\(\)/)
  assert.doesNotMatch(closeBody, /lightboxEditResultsBySession\.clear\(\)|lightboxEditOperations\.clear\(\)/)
  assert.match(resolveBody, /const resolve = lightboxAnnotationExportResolve/)
  assert.match(resolveBody, /clearLightboxAnnotationExport\(\)/)
  assert.match(resolveBody, /if \(resolve\) resolve\(dataUrl\)/)
  assert.match(appendBody, /sessionKey: lightboxEditSessionKey\.value/)
  assert.match(appendBody, /return lightboxEditResults\.value\[lightboxEditResults\.value\.length - 1\]/)
  assert.match(applyBody, /const queues = collectResultQueues\(latestJob\)/)
  assert.match(applyBody, /\.flatMap\(\(queue\) => queue\.items \|\| \[\]\)/)
  assert.match(applyBody, /\.find\(\(item\) => String\(item\?\.runUid \|\| item\?\.run_uid \|\| ''\) === String\(runUid \|\| ''\)\)/)
  assert.match(applyBody, /lightboxEditSessionKey\.value === placeholder\.sessionKey/)
  assert.match(applyBody, /activateLightboxEditPlaceholder\(placeholder\)/)
  assert.doesNotMatch(applyBody, /lightboxActiveIndex\.value = index \+ 1/)
})

test('AI image workbench isolates loading and completion state to the originating task', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const loadingStart = workbench.indexOf('const loadingResultCards = computed')
  const loadingEnd = workbench.indexOf('const loadingResultQueue', loadingStart)
  const loadingBody = workbench.slice(loadingStart, loadingEnd)
  const generateStart = workbench.indexOf('async function generate()')
  const generateEnd = workbench.indexOf('function normalizeGenerateError', generateStart)
  const generateBody = workbench.slice(generateStart, generateEnd)
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function removeReferencePath', editStart)
  const editBody = workbench.slice(editStart, editEnd)
  const overlayStart = workbench.indexOf('.aiw-edit-loading-overlay {')
  const overlayEnd = workbench.indexOf('.aiw-edit-spinner {', overlayStart)
  const overlayBody = workbench.slice(overlayStart, overlayEnd)

  assert.match(workbench, /import \{[\s\S]*generationBelongsToJob[\s\S]*\} from '\.\.\/utils\/aiImageLoadingState\.mjs'/)
  assert.match(workbench, /const generatingJobUid = ref\(''\)/)
  assert.match(workbench, /const generatingSnapshot = ref\(null\)/)
  assert.match(workbench, /const generationBelongsToCurrentJob = computed\(\(\) => generationBelongsToJob\(generatingJobUid\.value, activeJobUid\.value\)\)/)
  assert.match(loadingBody, /if \(!generationBelongsToCurrentJob\.value\) return \[\]/)
  assert.match(loadingBody, /const snapshot = generatingSnapshot\.value \|\| \{\}/)
  assert.match(generateBody, /generatingJobUid\.value = jobUid/)
  assert.match(generateBody, /generatingSnapshot\.value = submittedSnapshot/)
  assert.match(generateBody, /if \(activeJobUid\.value === jobUid\) currentJob\.value = latest \|\| activeTask/)
  assert.match(generateBody, /generatingJobUid\.value = ''/)
  assert.match(generateBody, /generatingSnapshot\.value = null/)
  assert.doesNotMatch(editBody, /generating\.value\s*=/)
  assert.doesNotMatch(editBody, /generatingJobUid\.value\s*=/)
  assert.doesNotMatch(editBody, /generatingSnapshot\.value\s*=/)
  assert.match(editBody, /if \(!submittedInputsCleared && activeJobUid\.value === jobUid\)/)
  assert.match(overlayBody, /justify-items: center/)
  assert.match(overlayBody, /text-align: center/)
})

test('AI image workbench scopes lightbox history and prompts to the selected edit branch', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const queueStart = workbench.indexOf('function collectResultQueues')
  const resultStart = workbench.indexOf('function collectResultCardsFromRun')
  const resultEnd = workbench.indexOf('function taskMetaLine', resultStart)
  const queueBody = workbench.slice(queueStart, resultStart)
  const resultBody = workbench.slice(resultStart, resultEnd)
  const previewStart = workbench.indexOf('const lightboxPreviewItems = computed')
  const previewEnd = workbench.indexOf('const lightboxActiveItem = computed', previewStart)
  const previewBody = workbench.slice(previewStart, previewEnd)
  const chainStart = workbench.indexOf('function promptChainForItem')
  const chainEnd = workbench.indexOf('function resetLightboxEditDraft', chainStart)
  const chainBody = workbench.slice(chainStart, chainEnd)
  const placeholderStart = workbench.indexOf('function appendLightboxEditPlaceholder')
  const placeholderEnd = workbench.indexOf('function applyLightboxEditResult', placeholderStart)
  const placeholderBody = workbench.slice(placeholderStart, placeholderEnd)
  const applyStart = workbench.indexOf('function applyLightboxEditResult')
  const applyEnd = workbench.indexOf('async function runLightboxEditGeneration', applyStart)
  const applyBody = workbench.slice(applyStart, applyEnd)
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function removeReferencePath', editStart)
  const editBody = workbench.slice(editStart, editEnd)

  assert.match(workbench, /from '\.\.\/aiImageResultLineage\.mjs'/)
  assert.match(workbench, /resolveResultLineage/)
  assert.match(workbench, /promptChainFromLineage/)
  assert.doesNotMatch(queueBody, /let historyItems = \[\]/)
  assert.match(queueBody, /resolveResultLineage\(item, flatItems\)/)
  assert.match(queueBody, /promptChainFromLineage\(lineage\)/)
  assert.match(resultBody, /jobUid: job\?\.job_uid \|\| ''/)
  assert.match(resultBody, /runUid: run\?\.run_uid \|\| run\?\.task_id \|\| ''/)
  assert.match(resultBody, /editSource: run\?\.edit_source \|\| null/)
  assert.match(previewBody, /lightboxHistoryItems\(lightboxItem\.value\)/)
  assert.match(previewBody, /dedupeLightboxItems/)
  assert.match(chainBody, /function promptChainForItem\(item\)/)
  assert.match(chainBody, /原图 Prompt/)
  assert.match(chainBody, /修改 Prompt/)
  assert.match(placeholderBody, /historyItems: buildLightboxEditHistory\(sourceItem\)/)
  assert.match(placeholderBody, /promptChain: buildLightboxPromptChain\(sourceItem, prompt\)/)
  assert.match(placeholderBody, /sourceJobUid: resultOwnerJobUid\(sourceItem\)/)
  assert.match(placeholderBody, /editSource: buildEditSource\(sourceItem\)/)
  assert.match(applyBody, /const editMetadata = preserveLightboxEditMetadata\(placeholder\)/)
  assert.match(applyBody, /\.\.\.editMetadata/)
  assert.match(editBody, /edit_source: buildEditSource\(sourceItem\)/)
})

test('AI image workbench appends edit runs to the source result queue', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const queueStart = workbench.indexOf('function collectResultQueues')
  const queueEnd = workbench.indexOf('function collectResultCardsFromRun', queueStart)
  const queueBody = workbench.slice(queueStart, queueEnd)
  const placeholderStart = workbench.indexOf('function workbenchRunPlaceholders')
  const placeholderEnd = workbench.indexOf('function collectResultQueues', placeholderStart)
  const placeholderBody = workbench.slice(placeholderStart, placeholderEnd)
  const applyStart = workbench.indexOf('function applyLightboxEditResult')
  const applyEnd = workbench.indexOf('async function runLightboxEditGeneration', applyStart)
  const applyBody = workbench.slice(applyStart, applyEnd)
  const statusStart = workbench.indexOf('const statusAnnouncement = computed')
  const statusEnd = workbench.indexOf('const errorAnnouncement = computed', statusStart)
  const statusBody = workbench.slice(statusStart, statusEnd)

  assert.match(workbench, /groupResultQueuesByLineage/)
  assert.match(queueBody, /return groupResultQueuesByLineage\(queues\)\.reverse\(\)/)
  assert.match(placeholderBody, /editSource: run\?\.edit_source \|\| null/)
  assert.match(applyBody, /\.flatMap\(\(queue\) => queue\.items \|\| \[\]\)/)
  assert.match(applyBody, /item\?\.runUid \|\| item\?\.run_uid/)
  assert.doesNotMatch(applyBody, /queues\.find\(\(queue\) => String\(queue\?\.key/)
  assert.match(statusBody, /visibleResultQueues\.value\.reduce/)
  assert.doesNotMatch(statusBody, /summary\.runs/)
})

test('AI image workbench embeds a tldraw annotation layer for precise edits', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const annotation = read('app/src/renderer/components/TldrawAnnotationLayer.js')
  const pkg = JSON.parse(read('app/package.json'))
  const submitStart = workbench.indexOf('async function submitLightboxEdit()')
  const submitEnd = workbench.indexOf('function removeReferencePath', submitStart)
  const submitBody = workbench.slice(submitStart, submitEnd)
  const resetAnnotationStart = workbench.indexOf('function resetLightboxAnnotationState')
  const resetAnnotationEnd = workbench.indexOf('function setLightboxAnnotationTool', resetAnnotationStart)
  const resetAnnotationBody = workbench.slice(resetAnnotationStart, resetAnnotationEnd)
  const setToolStart = workbench.indexOf('function setLightboxAnnotationTool')
  const setToolEnd = workbench.indexOf('function setLightboxAnnotationColor', setToolStart)
  const setToolBody = workbench.slice(setToolStart, setToolEnd)

  assert.match(workbench, /import TldrawAnnotationLayer from '\.\.\/components\/TldrawAnnotationLayer\.js'/)
  assert.match(workbench, /<TldrawAnnotationLayer/)
  assert.match(workbench, /class="aiw-lightbox-main-image"/)
  assert.ok(
    workbench.indexOf('class="aiw-lightbox-main-image"') < workbench.indexOf('<TldrawAnnotationLayer'),
    'the original image should render beneath the transparent annotation layer',
  )
  assert.match(workbench, /class="aiw-lightbox-annotation-layer"/)
  assert.match(workbench, /:class="\{ active: Boolean\(lightboxAnnotationTool\) \}"/)
  assert.match(workbench, /:active-tool="lightboxAnnotationTool"/)
  assert.match(workbench, /:annotation-color="lightboxAnnotationColor"/)
  assert.match(workbench, /:clear-nonce="lightboxAnnotationClearNonce"/)
  assert.match(workbench, /class="aiw-lightbox-annotation-toolbar"/)
  assert.match(workbench, /class="aiw-annotation-color-strip"/)
  assert.match(workbench, /v-for="color in AIW_ANNOTATION_COLORS"/)
  assert.match(workbench, /setLightboxAnnotationColor\(color\.id\)/)
  assert.match(workbench, /setLightboxAnnotationTool\('draw'\)/)
  assert.match(workbench, /setLightboxAnnotationTool\('arrow'\)/)
  assert.match(workbench, /setLightboxAnnotationTool\('text'\)/)
  assert.match(workbench, /clearLightboxAnnotation/)
  assert.match(workbench, /exitLightboxAnnotation/)
  assert.match(workbench, /@export-annotation="captureLightboxAnnotation"/)
  assert.match(workbench, /const lightboxAnnotationDataUrl = ref\(''\)/)
  assert.match(workbench, /const lightboxAnnotationTool = ref\('draw'\)/)
  assert.match(resetAnnotationBody, /lightboxAnnotationTool\.value = 'draw'/)
  assert.match(setToolBody, /lightboxAnnotationTool\.value = tool/)
  assert.doesNotMatch(setToolBody, /lightboxAnnotationTool\.value === tool \? '' : tool/)
  assert.match(workbench, /const lightboxAnnotationColor = ref\('red'\)/)
  assert.match(workbench, /const AIW_ANNOTATION_COLORS = \[/)
  assert.match(workbench, /const lightboxAnnotationClearNonce = ref\(0\)/)
  assert.match(workbench, /async function materializeLightboxAnnotation/)
  assert.match(submitBody, /await materializeLightboxAnnotation/)
  assert.match(annotation, /Box,[\s\S]*DefaultColorStyle,[\s\S]*DefaultDashStyle,[\s\S]*DefaultSizeStyle,[\s\S]*Tldraw[\s\S]*from 'tldraw'/)
  assert.match(annotation, /from 'react-dom\/client'/)
  assert.match(annotation, /tldraw\/tldraw\.css/)
  assert.match(annotation, /from '@tldraw\/assets\/urls'/)
  assert.doesNotMatch(annotation, /@tldraw\/assets\/imports\.vite/)
  assert.doesNotMatch(annotation, /const assetUrls = getAssetUrlsByImport\(\)/)
  assert.match(annotation, /new Box\(0, 0, rect\.width, rect\.height\)/)
  assert.doesNotMatch(annotation, /\? \{ x: 0, y: 0, w: rect\.width, h: rect\.height \}/)
  assert.match(annotation, /const LOCKED_ANNOTATION_CAMERA_OPTIONS = Object\.freeze/)
  assert.match(annotation, /wheelBehavior: 'none'/)
  assert.match(annotation, /isLocked: true/)
  assert.match(annotation, /panSpeed: 0/)
  assert.match(annotation, /zoomSpeed: 0/)
  assert.match(annotation, /zoomSteps: \[1\]/)
  assert.match(annotation, /function resetCamera\(editor\)/)
  assert.match(annotation, /editor\.setCameraOptions\(LOCKED_ANNOTATION_CAMERA_OPTIONS\)/)
  assert.match(annotation, /force: true/)
  assert.match(annotation, /const stopCameraGesture = useCallback\(\(event\) => \{/)
  assert.match(annotation, /event\.preventDefault\(\)/)
  assert.match(annotation, /event\.stopImmediatePropagation\?\.\(\)/)
  assert.match(annotation, /addEventListener\('wheel', stopCameraGesture, \{ capture: true, passive: false \}\)/)
  assert.match(annotation, /camera: LOCKED_ANNOTATION_CAMERA_OPTIONS/)
  assert.match(annotation, /editor\.setStyleForNextShapes\(DefaultColorStyle, annotationColor/)
  assert.match(annotation, /editor\.setStyleForSelectedShapes\(DefaultColorStyle, annotationColor/)
  assert.match(annotation, /editor\.setStyleForNextShapes\(DefaultDashStyle, 'draw'/)
  assert.match(annotation, /editor\.setStyleForNextShapes\(DefaultSizeStyle, 'l'/)
  assert.match(annotation, /editor\.toImageDataUrl/)
  assert.doesNotMatch(annotation, /AssetRecordType/)
  assert.doesNotMatch(annotation, /createShapeId/)
  assert.doesNotMatch(annotation, /editor\.createAssets/)
  assert.doesNotMatch(annotation, /type: 'image'/)
  assert.ok(pkg.dependencies?.tldraw, 'tldraw should be bundled as a client dependency')
  assert.ok(pkg.dependencies?.react, 'react should be bundled for the tldraw island')
  assert.ok(pkg.dependencies?.['react-dom'], 'react-dom should be bundled for the tldraw island')
})

test('AI image workbench keeps generated task metadata separate from next-run edits', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const taskRecordsStart = workbench.indexOf('const taskRecords = computed')
  const taskRecordsEnd = workbench.indexOf('onMounted', taskRecordsStart)
  const taskRecordsBody = workbench.slice(taskRecordsStart, taskRecordsEnd)
  const restoreStart = workbench.indexOf('async function restoreJob(job, options = {})')
  const restoreEnd = workbench.indexOf('function openOutputFolder', restoreStart)
  const restoreBody = workbench.slice(restoreStart, restoreEnd)

  assert.match(workbench, /function hasGeneratedResults\(job = \{\}\)/)
  assert.match(workbench, /if \(!options\.includeGeneratedDrafts && hasGeneratedResults\(job\)\) return job/)
  assert.match(taskRecordsBody, /mergeJobWithDraft\(source, \{ includeGeneratedDrafts: false \}\)/)
  assert.match(taskRecordsBody, /mergeJobWithDraft\(currentJob\.value, \{ includeGeneratedDrafts: false \}\)/)
  assert.match(restoreBody, /const formDetail = mergeJobWithDraft\(detail, \{ includeGeneratedDrafts: true \}\)/)
  assert.match(restoreBody, /currentJob\.value = detail/)
  assert.match(workbench, /任务：\{\{ persistedCurrentJob\?\.title \|\| form\.title \|\| '本次生成' \}\}/)
  assert.doesNotMatch(workbench, /\{\{ generatedSummaryLine \}\}/)
  assert.doesNotMatch(workbench, /const generatedSummaryLine = computed/)
  assert.match(workbench, /<span>下次生成参数<\/span>/)
})

test('AI image workbench hydrates a restored task placeholder from persisted job metadata', async () => {
  const resultState = await import('../app/src/renderer/aiImageResultLineage.mjs')
  assert.equal(typeof resultState.mergeCurrentJobRecord, 'function')

  const persistedJob = {
    job_uid: 'task-6',
    title: 'AI 生图任务 6',
    model_key: 'gpt-image-2',
    status: 'completed',
    params: { ratio: '3:4', size: '1536x2048', n: 1 },
    summary: {
      runs: [{ image_urls: ['https://img.example/result.png'] }],
    },
  }
  const restoredPlaceholder = { job_uid: 'task-6', status: 'draft' }

  assert.deepEqual(
    resultState.mergeCurrentJobRecord(restoredPlaceholder, [persistedJob]),
    {
      ...persistedJob,
      status: 'draft',
    },
  )

  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  assert.match(workbench, /const persistedCurrentJob = computed/)
  assert.match(workbench, /mergeCurrentJobRecord\(currentJob\.value, jobs\.value\)/)
  assert.match(workbench, /hasGeneratedResults\(persistedCurrentJob\.value\)/)
})

test('AI image workbench saves current count before provider request', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const buildPayloadStart = workbench.indexOf('function buildJobPayload')
  const buildPayloadEnd = workbench.indexOf('function scheduleTaskAutosave', buildPayloadStart)
  const buildPayloadBody = workbench.slice(buildPayloadStart, buildPayloadEnd)
  const ensureStart = workbench.indexOf('async function ensureCurrentTask()')
  const ensureEnd = workbench.indexOf('async function createTaskFromCurrentForm', ensureStart)
  const ensureBody = workbench.slice(ensureStart, ensureEnd)
  const autosaveStart = workbench.indexOf('async function autosaveCurrentTask')
  const autosaveEnd = workbench.indexOf('function upsertJob', autosaveStart)
  const autosaveBody = workbench.slice(autosaveStart, autosaveEnd)

  assert.match(workbench, /function normalizeImageCount\(value\)/)
  assert.match(buildPayloadBody, /const requestedCount = activeNanoBanana\.value \? 1 : normalizeImageCount\(form\.count\)/)
  assert.ok(
    buildPayloadBody.indexOf('...parseAdvancedJson') < buildPayloadBody.indexOf('n: requestedCount'),
    'advanced JSON must not override the count control',
  )
  assert.match(buildPayloadBody, /params\.n = requestedCount/)
  assert.match(autosaveBody, /if \(!options\.allowDuringGeneration && generating\.value\) return null/)
  assert.match(autosaveBody, /if \(!options\.force && hasGeneratedResults\(persistedCurrentJob\.value\)\) return null/)
  assert.match(ensureBody, /autosaveCurrentTask\(\{ force: true, allowDuringGeneration: true \}\)/)
})

test('AI image workbench exposes a clear clickable full prompt affordance', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const promptRowStart = workbench.indexOf('class="aiw-result-prompt-row"')
  const promptRowEnd = workbench.indexOf('</div>', promptRowStart)
  const promptRowBody = workbench.slice(promptRowStart, promptRowEnd)

  assert.match(workbench, /const promptDialogQueue = ref\(null\)/)
  assert.match(workbench, /const promptDialogPrompt = computed\(\(\) => queuePromptText\(promptDialogQueue\.value\)\)/)
  assert.match(workbench, /class="aiw-result-prompt-row"/)
  assert.match(promptRowBody, /class="aiw-prompt-preview-button"/)
  assert.match(promptRowBody, /@click="openPromptDialog\(queue\)"/)
  assert.match(promptRowBody, /查看完整/)
  assert.match(promptRowBody, /<AiwIcon name="eye"/)
  assert.doesNotMatch(promptRowBody, /shouldShowPromptDialog\(queue\)/)
  assert.match(workbench, /class="aiw-prompt-dialog"/)
  assert.match(workbench, /role="dialog" aria-modal="true" aria-label="完整 Prompt"/)
  assert.match(workbench, /function queuePromptPreview\(queue = \{\}\)/)
  assert.match(workbench, /function openPromptDialog\(queue\)/)
  assert.match(workbench, /function closePromptDialog\(\)/)
})

test('AI image workbench prefers persistent local cache and rebuilds it after remote success', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const previewStart = workbench.indexOf('function resultPreviewCandidates(item)')
  const previewEnd = workbench.indexOf('function toggleResult', previewStart)
  const previewBody = workbench.slice(previewStart, previewEnd)

  assert.match(workbench, /const resultCachePaths = reactive\(\{\}\)/)
  assert.match(workbench, /const resultCachePending = reactive\(new Set\(\)\)/)
  assert.match(workbench, /function mergeResultCacheFromJob\(job\)/)
  assert.match(workbench, /function resultPreviewCandidates\(item\)/)
  assert.match(previewBody, /cachedResultPath\(item\?\.url\)/)
  assert.match(previewBody, /return \[cachedResultPath\(item\?\.url\), item\?\.path, item\?\.url\]/)
  assert.match(workbench, /function resultPreviewSrc\(item\)/)
  assert.match(workbench, /function markResultPreviewBroken\(item\)/)
  assert.match(workbench, /function handleResultPreviewLoaded\(item\)/)
  assert.match(workbench, /function queueResultCache\(item\)/)
  assert.match(workbench, /window\.cs\.materializeAiImageResult/)
  assert.match(workbench, /resultPreviewCandidates\(item\)\.forEach/)
  assert.match(workbench, /:src="resultPreviewSrc\(item\)"/)
  assert.match(workbench, /@error="markResultPreviewBroken\(item\)"/)
  assert.match(workbench, /@load="handleResultPreviewLoaded\(item\)"/)
  assert.match(workbench, /loading="lazy"/)
  assert.match(workbench, /decoding="async"/)
})

test('AI image workbench materializes URL results before using them as input images', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const materializeStart = workbench.indexOf('async function materializeResultForInput(item)')
  const materializeEnd = workbench.indexOf('async function saveAs(items)', materializeStart)
  const materializeBody = workbench.slice(materializeStart, materializeEnd)
  const setAsMainStart = workbench.indexOf('async function setAsMain(item)')
  const setAsMainEnd = workbench.indexOf('async function addAsReference(item)', setAsMainStart)
  const setAsMainBody = workbench.slice(setAsMainStart, setAsMainEnd)
  const addRefStart = workbench.indexOf('async function addAsReference(item)')
  const addRefEnd = workbench.indexOf('function removeReferencePath', addRefStart)
  const addRefBody = workbench.slice(addRefStart, addRefEnd)

  assert.notEqual(materializeStart, -1, 'materializeResultForInput should exist')
  assert.match(materializeBody, /window\.cs\.materializeAiImageResult/)
  assert.match(workbench, /function resultOwnerJobUid\(item\)/)
  assert.match(materializeBody, /const ownerJobUid = resultOwnerJobUid\(item\)/)
  assert.match(materializeBody, /window\.cs\.materializeAiImageResult\(ownerJobUid,/)
  assert.doesNotMatch(materializeBody, /window\.cs\.materializeAiImageResult\(currentJob\.value\.job_uid,/)
  assert.match(materializeBody, /file: resultKey\(item\)/)
  assert.match(materializeBody, /return result\?\.path \|\| item\?\.path \|\| ''/)
  assert.match(setAsMainBody, /const key = await materializeResultForInput\(item\)/)
  assert.match(addRefBody, /const key = await materializeResultForInput\(item\)/)
  assert.doesNotMatch(setAsMainBody, /form\.mainImagePath = resultKey\(item\)/)
  assert.doesNotMatch(addRefBody, /form\.referenceImagePaths\.push\(resultKey\(item\)\)/)
})

test('AI image workbench supports dragging generated results into main and reference slots', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const resultCardStart = workbench.indexOf('class="aiw-result-card"')
  const resultCardEnd = workbench.indexOf('>', resultCardStart)
  const resultCardBody = workbench.slice(resultCardStart, resultCardEnd)
  const previewButtonStart = workbench.indexOf('class="aiw-preview-button"')
  const previewButtonEnd = workbench.indexOf('>', previewButtonStart)
  const previewButtonBody = workbench.slice(previewButtonStart, previewButtonEnd)
  const dragStart = workbench.indexOf('function startResultDrag(item, event)')
  const dragEnd = workbench.indexOf('async function dropResultAsMain')
  const dragBody = workbench.slice(dragStart, dragEnd)
  const dropMainStart = workbench.indexOf('async function dropResultAsMain')
  const dropReferenceStart = workbench.indexOf('async function dropResultAsReference')
  const dropMainBody = workbench.slice(dropMainStart, dropReferenceStart)
  const dropReferenceBody = workbench.slice(dropReferenceStart, workbench.indexOf('function removeReferencePath', dropReferenceStart))

  assert.match(workbench, /const draggingResultKey = ref\(''\)/)
  assert.match(resultCardBody, /:draggable="!item\.loading && !item\.failed"/)
  assert.match(resultCardBody, /@dragstart\.stop="startResultDrag\(item, \$event\)"/)
  assert.match(resultCardBody, /@dragend="endResultDrag"/)
  assert.match(previewButtonBody, /:draggable="!item\.loading"/)
  assert.match(previewButtonBody, /@dragstart\.stop="startResultDrag\(item, \$event\)"/)
  assert.match(previewButtonBody, /@dragend="endResultDrag"/)
  assert.match(workbench, /@dragover\.prevent="handleResultDragOver"/)
  assert.match(workbench, /@drop\.prevent="dropResultAsMain"/)
  assert.match(workbench, /@drop\.prevent="dropResultAsReference"/)
  assert.match(workbench, /class="\{ 'drag-over': dragOverTarget === 'main' \}"/)
  assert.match(workbench, /class="\{ 'drag-over': dragOverTarget === 'reference' \}"/)
  assert.notEqual(dragStart, -1, 'startResultDrag should exist')
  assert.match(dragBody, /event\.dataTransfer\.setData\('text\/plain', key\)/)
  assert.match(dragBody, /event\.dataTransfer\.effectAllowed = 'copy'/)
  assert.match(dropMainBody, /const item = resolveDroppedResult\(event\)/)
  assert.match(dropMainBody, /await setAsMain\(item\)/)
  assert.match(dropReferenceBody, /const item = resolveDroppedResult\(event\)/)
  assert.match(dropReferenceBody, /await addAsReference\(item\)/)
})

test('AI image workbench recreates stale persisted jobs before running', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')

  assert.match(workbench, /function isAiImageJobNotFoundError\(error\)/)
  assert.match(workbench, /function forgetStaleJob\(jobUid\)/)
  assert.match(workbench, /const existing = await window\.cs\.getAiImageJob\(currentJob\.value\.job_uid\)/)
  assert.match(workbench, /if \(!isAiImageJobNotFoundError\(error\)\) throw error/)
  assert.match(workbench, /const created = await createTaskFromCurrentForm\('draft'\)/)
  assert.match(workbench, /当前任务记录不存在，请重新新建任务后再生成/)
})

test('AI image workbench keeps result card actions and metadata compact', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const cardActionsStart = workbench.indexOf('class="aiw-result-card-actions"')
  const cardActionsEnd = workbench.indexOf('</div>', cardActionsStart)
  const cardActionsBody = workbench.slice(cardActionsStart, cardActionsEnd)

  assert.match(workbench, /class="aiw-result-card-meta"/)
  assert.match(workbench, /class="aiw-result-card-actions"/)
  assert.ok(
    cardActionsBody.indexOf('设为主图') < cardActionsBody.indexOf('设为参考')
      && cardActionsBody.indexOf('设为参考') < cardActionsBody.indexOf('修改')
      && cardActionsBody.indexOf('修改') < cardActionsBody.indexOf('下载'),
    'result card actions should be ordered as set main, set reference, edit, download',
  )
  assert.match(cardActionsBody, /<AiwIcon name="image"/)
  assert.match(cardActionsBody, /<AiwIcon name="plus"/)
  assert.match(cardActionsBody, /<AiwIcon name="edit"/)
  assert.match(cardActionsBody, /<AiwIcon name="download"/)
  assert.doesNotMatch(workbench, />加入参考图</)
  assert.doesNotMatch(workbench, />另存为<\/button>/)
  assert.match(workbench, /\.aiw-result-list\s*\{[\s\S]*grid-template-columns: repeat\(auto-fill, minmax\(300px, 350px\)\)/)
  assert.doesNotMatch(workbench, /\.aiw-result-list\s*\{[\s\S]*grid-template-columns: repeat\(auto-fill, minmax\(300px, 1fr\)\)/)
  assert.match(workbench, /\.aiw-result-card-actions\s*\{[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(workbench, /\.aiw-result-card-meta\s*\{[\s\S]*flex-direction: row/)
  assert.match(workbench, /const AiwIcon =/)
  assert.match(workbench, /\.aiw-button-icon\s*\{[\s\S]*width: 14px/)
  assert.match(workbench, /\.aiw-icon-button-content\s*\{[\s\S]*display: inline-flex/)
})

test('AI image workbench uses icons on primary page actions', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const topActionsStart = workbench.indexOf('class="aiw-top-actions"')
  const topActionsEnd = workbench.indexOf('</div>', topActionsStart)
  const topActionsBody = workbench.slice(topActionsStart, topActionsEnd)
  const resultsActionsStart = workbench.indexOf('class="aiw-results-actions"')
  const resultsActionsEnd = workbench.indexOf('class="aiw-workspace-body"', resultsActionsStart)
  const resultsActionsBody = workbench.slice(resultsActionsStart, resultsActionsEnd)

  assert.match(topActionsBody, /<AiwIcon name="plus"/)
  assert.match(topActionsBody, /<AiwIcon name="folder"/)
  assert.match(topActionsBody, /<AiwIcon name="settings"/)
  assert.match(resultsActionsBody, /<AiwIcon :name="allVisibleSelected \? 'minus-square' : 'check-square'"/)
  assert.match(resultsActionsBody, /<AiwIcon name="download"/)
  assert.match(resultsActionsBody, /<AiwIcon name="sidebar"/)
  assert.match(workbench, /<AiwIcon name="wand"/)
})

test('AI image workbench uses the task button to toggle the history sidebar', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const resultsActionsStart = workbench.indexOf('class="aiw-results-actions"')
  const resultsActionsEnd = workbench.indexOf('class="aiw-workspace-body"', resultsActionsStart)
  const resultsActionsBody = workbench.slice(resultsActionsStart, resultsActionsEnd)

  assert.match(workbench, /const taskSidebarOpen = ref\(true\)/)
  assert.match(workbench, /function toggleTaskSidebar\(\)/)
  assert.match(resultsActionsBody, /class="aiw-task-sidebar-toggle"/)
  assert.match(resultsActionsBody, /:class="\{ active: taskSidebarToggleActive \}"/)
  assert.match(resultsActionsBody, /:aria-pressed="taskSidebarToggleActive \? 'true' : 'false'"/)
  assert.match(resultsActionsBody, /@click="toggleTaskSidebar"/)
  assert.match(resultsActionsBody, /<AiwIcon name="sidebar"/)
  assert.match(resultsActionsBody, />任务/)
  assert.match(workbench, /<aside v-show="taskSidebarOpen" class="aiw-history-sidebar">/)
  assert.doesNotMatch(workbench, /<aside v-if="taskSidebarOpen" class="aiw-history-sidebar">/)
  assert.doesNotMatch(workbench, /class="aiw-tabs"/)
  assert.doesNotMatch(workbench, /workspaceMode === 'results'/)
  assert.doesNotMatch(workbench, /workspaceMode === 'tasks'/)
  assert.doesNotMatch(workbench, /workspaceMode === 'logs'/)
  assert.doesNotMatch(workbench, /const workspaceMode/)
  assert.doesNotMatch(workbench, /class="aiw-log-panel"/)
  assert.doesNotMatch(workbench, /class="aiw-log-stack"/)
})

test('AI image workbench keeps task records as a persistent right-side menu', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const workspaceBodyStart = workbench.indexOf('class="aiw-workspace-body"')
  const resultsStart = workbench.indexOf('class="aiw-result-wall"', workspaceBodyStart)
  const detailStart = workbench.indexOf('class="aiw-task-detail-panel"', workspaceBodyStart)
  const sidebarStart = workbench.indexOf('v-show="taskSidebarOpen"', workspaceBodyStart)
  const sidebarEnd = workbench.indexOf('</aside>', sidebarStart)
  const sidebarBody = workbench.slice(sidebarStart, sidebarEnd)
  const mediumMediaStart = workbench.indexOf('@media (max-width: 1060px)')
  const narrowMediaStart = workbench.indexOf('@media (max-width: 760px)')
  const reduceMotionMediaStart = workbench.indexOf('@media (prefers-reduced-motion: reduce)')
  const mediumMediaBody = workbench.slice(mediumMediaStart, narrowMediaStart)
  const narrowMediaBody = workbench.slice(narrowMediaStart, reduceMotionMediaStart)

  assert.match(workbench, /class="aiw-workspace-body"/)
  assert.match(workbench, /:class="\{ 'history-collapsed': !taskSidebarOpen \}"/)
  assert.match(workbench, /class="aiw-result-wall"/)
  assert.doesNotMatch(workbench, /class="aiw-task-detail-panel"/)
  assert.match(workbench, /v-show="taskSidebarOpen" class="aiw-history-sidebar"/)
  assert.doesNotMatch(sidebarBody, /class="aiw-history-actions"/)
  assert.doesNotMatch(sidebarBody, /@click="createNewTask"/)
  assert.doesNotMatch(sidebarBody, /@click="loadJobs"/)
  assert.doesNotMatch(workbench, /\.aiw-history-actions/)
  assert.match(workbench, /@click="selectTaskRecord\(job\)"/)
  assert.match(workbench, /async function selectTaskRecord\(job\)/)
  assert.doesNotMatch(workbench, /workspaceMode\.value = 'results'[\s\S]*await restoreJob\(job\)/)
  assert.doesNotMatch(workbench, />查看结果</)
  assert.doesNotMatch(workbench, /stayInTasks: true/)
  assert.ok(resultsStart > 0 && sidebarStart > 0 && resultsStart < sidebarStart, 'result wall should render before the persistent task menu')
  assert.equal(detailStart, -1, 'task detail page should be removed')
  assert.match(workbench, /\.aiw-workspace-body\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(220px, 240px\)/)
  assert.match(workbench, /\.aiw-workspace-body\.history-collapsed\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.notEqual(mediumMediaStart, -1, 'medium layout breakpoint should exist')
  assert.notEqual(narrowMediaStart, -1, 'narrow layout breakpoint should exist')
  assert.doesNotMatch(mediumMediaBody, /\.aiw-workspace-body/, 'desktop and medium widths should keep the task list as a right-side menu instead of folding it below results')
  assert.match(narrowMediaBody, /\.aiw-workspace-body\s*\{[\s\S]*position: relative;[\s\S]*display: block/)
  assert.match(narrowMediaBody, /\.aiw-history-sidebar\s*\{[\s\S]*position: absolute;[\s\S]*display: none/)
  assert.match(narrowMediaBody, /\.aiw-main-grid\.compact-history \.aiw-history-sidebar\s*\{[\s\S]*display: flex/)
  assert.match(narrowMediaBody, /\.aiw-main-grid\.compact-history \.aiw-result-wall\s*\{[\s\S]*display: none/)
  assert.doesNotMatch(workbench, /class="aiw-task-records-workspace"/)
  assert.doesNotMatch(workbench, /class="aiw-history-drawer"/)
  assert.doesNotMatch(workbench, /class="aiw-history-toggle"/)
  assert.doesNotMatch(workbench, /grid-template-columns: minmax\(300px, 340px\) minmax\(420px, 1fr\) minmax\(230px, 260px\)/)
  assert.match(workbench, /@media \(max-width: 1060px\)/)
})

test('AI image task cards expose persistent pinning and guarded deletion controls', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const sidebarStart = workbench.indexOf('<aside v-show="taskSidebarOpen" class="aiw-history-sidebar">')
  const sidebarEnd = workbench.indexOf('</aside>', sidebarStart)
  const sidebarBody = workbench.slice(sidebarStart, sidebarEnd)
  const deleteStart = workbench.indexOf('async function confirmDeleteTask()')
  const deleteEnd = workbench.indexOf('function syncNarrowWorkbench', deleteStart)
  const deleteBody = workbench.slice(deleteStart, deleteEnd)
  const taskActionStyleStart = workbench.indexOf('.aiw-history-pin,')
  const taskActionStyleEnd = workbench.indexOf('.aiw-history-thumbs', taskActionStyleStart)
  const taskActionStyles = workbench.slice(taskActionStyleStart, taskActionStyleEnd)

  assert.match(sidebarBody, /<article[\s\S]*class="aiw-history-item"/)
  assert.match(sidebarBody, /class="aiw-history-select"/)
  assert.match(sidebarBody, /class="aiw-history-pin"/)
  assert.match(sidebarBody, /\{\{ job\.pinned_at \? '取消置顶' : '置顶' \}\}/)
  assert.match(sidebarBody, /@click\.stop="toggleTaskPinned\(job\)"/)
  assert.match(sidebarBody, /class="aiw-history-delete"/)
  assert.match(sidebarBody, /@click\.stop="openDeleteTaskDialog\(job, \$event\)"/)
  assert.match(sidebarBody, /:disabled="hasActiveRuns\(job\)"/)
  assert.doesNotMatch(sidebarBody, /<button[\s\S]*class="aiw-history-item"/)
  assert.match(workbench, /window\.cs\.setAiImageJobPinned\(job\.job_uid, !job\.pinned_at\)/)
  assert.match(workbench, /role="dialog"\s+aria-modal="true"\s+aria-label="确认删除 AI 生图任务"/)
  assert.match(workbench, /已下载或另存到本地文件夹的图片不受影响/)
  assert.match(deleteBody, /window\.cs\.deleteAiImageJob\(job\.job_uid\)/)
  assert.match(deleteBody, /await removeDeletedTaskState\(job\)/)
  assert.match(deleteBody, /deleted_cache_files/)
  assert.match(workbench, /\.aiw-history-pin\s*\{[\s\S]*top:/)
  assert.match(workbench, /\.aiw-history-delete\s*\{[\s\S]*bottom:/)
  assert.match(taskActionStyles, /color: var\(--text2\)/)
  assert.match(taskActionStyles, /\.aiw-history-pin:not\(:disabled\):hover,\s*\.aiw-history-delete:not\(:disabled\):hover\s*\{[\s\S]*transform: translateY\(-1px\)/)
  assert.doesNotMatch(taskActionStyles, /color: #ff6b5f/)
})

test('AI image workbench tells the model that annotation marks are placement-only references', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const editStart = workbench.indexOf('async function runLightboxEditGeneration')
  const editEnd = workbench.indexOf('function removeReferencePath', editStart)
  const editBody = workbench.slice(editStart, editEnd)

  assert.match(workbench, /const AIW_ANNOTATION_PROMPT_GUIDANCE =/)
  assert.match(workbench, /function buildAnnotationEditPrompt\(prompt, hasAnnotation\)/)
  assert.match(workbench, /标注参考图仅用于定位/)
  assert.match(workbench, /不要在结果中保留或复刻/)
  assert.match(editBody, /const effectivePrompt = buildAnnotationEditPrompt\(prompt, Boolean\(annotationPath\)\)/)
  assert.match(editBody, /form\.prompt = effectivePrompt/)
  assert.match(editBody, /prompt: effectivePrompt/)
})

test('AI image workbench simplifies top actions and reports open-folder failures', () => {
  const workbench = read('app/src/renderer/views/AiImageWorkbench.vue')
  const openStart = workbench.indexOf('async function openOutputFolder()')
  const openEnd = workbench.indexOf('function pathLabel', openStart)
  const openBody = workbench.slice(openStart, openEnd)

  assert.match(workbench, /class="aiw-top-primary" type="button" @click="createNewTask"[\s\S]*<AiwIcon name="plus" \/>新建任务/)
  assert.match(workbench, /<AiwIcon name="settings" \/>配置/)
  assert.doesNotMatch(workbench, />配置模型 Key<\/button>/)
  assert.notEqual(openStart, -1, 'openOutputFolder should be async')
  assert.match(openBody, /const directory = form\.output_dir \|\| currentJob\.value\?\.output_dir \|\| ''/)
  assert.match(openBody, /window\.cs\.openFile/)
  assert.match(openBody, /window\.cs\.revealFile/)
  assert.match(openBody, /throw new Error\('当前环境不支持直接打开输出文件夹'\)/)
  assert.match(openBody, /logs\.value\.push\(`打开输出文件夹/)
  assert.match(openBody, /errorMessage\.value = error\.message \|\| String\(error\)/)
})
