const assert = require('node:assert/strict')
const fs = require('node:fs')
const test = require('node:test')

const workbench = fs.readFileSync('app/src/renderer/views/AiImageWorkbench.vue', 'utf8')
const promptPicker = fs.readFileSync('app/src/renderer/components/PromptLibraryPickerModal.vue', 'utf8')

test('all workbench dialogs trap focus, close with Escape, restore focus, and inert their background', () => {
  assert.match(workbench, /focusFirstInDialog/)
  assert.match(workbench, /trapDialogFocus/)
  assert.match(workbench, /const batchDialogPanel = ref\(null\)/)
  assert.match(workbench, /const lightboxDialogPanel = ref\(null\)/)
  assert.match(workbench, /const promptDialogPanel = ref\(null\)/)
  assert.match(workbench, /const deleteTaskDialogPanel = ref\(null\)/)
  assert.match(workbench, /ref="batchDialogPanel"/)
  assert.match(workbench, /ref="lightboxDialogPanel"/)
  assert.match(workbench, /ref="promptDialogPanel"/)
  assert.match(workbench, /ref="deleteTaskDialogPanel"/)
  assert.match(workbench, /watch\(\(\) => deleteTaskDialog\.open, \(open\) => syncDialogFocus\('deleteTask'/)
  assert.match(workbench, /if \(deleteTaskDialog\.open\) return \{ key: 'deleteTask', panel: deleteTaskDialogPanel\.value, close: closeDeleteTaskDialog, busy: deleteTaskDialog\.submitting \}/)
  assert.match(workbench, /role="dialog"\s+aria-modal="true"\s+aria-label="确认删除 AI 生图任务"/)
  assert.match(workbench, /event\.key === 'Escape'/)
  assert.match(workbench, /dialogReturnFocus/)
  assert.match(workbench, /document\.addEventListener\('keydown', handleWorkbenchDialogKeydown/)
  assert.match(workbench, /document\.removeEventListener\('keydown', handleWorkbenchDialogKeydown/)
  assert.match(workbench, /:inert="workbenchDialogOpen \|\| undefined"/)
  assert.match(workbench, /:aria-hidden="workbenchDialogOpen \? 'true' : undefined"/)
})

test('Prompt library dialog owns Escape and focus containment without exposing background controls', () => {
  assert.match(promptPicker, /focusFirstInDialog/)
  assert.match(promptPicker, /trapDialogFocus/)
  assert.match(promptPicker, /ref="dialogPanel"/)
  assert.match(promptPicker, /event\.key === 'Escape'/)
  assert.match(promptPicker, /event\.stopImmediatePropagation\(\)/)
  assert.match(promptPicker, /document\.addEventListener\('keydown', handleDialogKeydown/)
  assert.match(promptPicker, /document\.removeEventListener\('keydown', handleDialogKeydown/)
})

test('result cards avoid nested button semantics and announce dynamic status', () => {
  const cardStart = workbench.indexOf('class="aiw-result-card"')
  const cardEnd = workbench.indexOf('</article>', cardStart)
  const card = workbench.slice(cardStart, cardEnd)
  assert.doesNotMatch(card, /role="button"/)
  assert.doesNotMatch(card, /@click="toggleResult\(item\)"/)
  assert.match(card, /class="aiw-select-toggle"[\s\S]*:aria-pressed=/)
  assert.match(workbench, /class="aiw-sr-only"[\s\S]*aria-live="polite"/)
  assert.match(workbench, /class="aiw-sr-only"[\s\S]*aria-live="assertive"/)
})

test('primary controls meet contrast and all motion respects reduced-motion preference', () => {
  assert.match(workbench, /\.aiw-primary-action,[\s\S]*background:\s*var\(--orange\);[\s\S]*color:\s*var\(--on-orange\);/)
  assert.match(workbench, /@media \(prefers-reduced-motion: reduce\)[\s\S]*animation-duration:\s*0\.01ms !important;/)
  assert.match(workbench, /@media \(prefers-reduced-motion: reduce\)[\s\S]*transition-duration:\s*0\.01ms !important;/)
})
