import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import test from 'node:test'

test('AI buyer show workflow is exposed under the AI workflow navigation group', async () => {
  const appSource = await readFile(new URL('../App.vue', import.meta.url), 'utf8')
  const agentSource = await readFile(new URL('../views/AgentWebView.vue', import.meta.url), 'utf8')
  const slotsSource = await readFile(new URL('../../../../integrations/deepseek-harness/crawshrimp-slots/lib/client.js', import.meta.url), 'utf8')

  assert.match(appSource, /import BuyerShowWorkflow from '\.\/views\/BuyerShowWorkflow\.vue'/)
  assert.match(appSource, /currentView === 'buyer_show_workflow'/)
  assert.match(appSource, /id: 'ai_workflows'[\s\S]*label: 'AI 工作流'[\s\S]*children: \[/)
  assert.match(appSource, /children: \[[\s\S]*\{ id: 'ai_video', icon: '🎞️', label: 'AI 视频工作流' \}[\s\S]*\{ id: 'buyer_show_workflow', icon: '🛍️', label: 'AI 买家秀工作流' \}/)
  assert.match(appSource, /function findNavItemById\(navId\)/)
  assert.match(appSource, /<BuyerShowWorkflow\s+v-if="currentView === 'buyer_show_workflow'"/)
  assert.match(agentSource, /const expandedFallbackNavGroupIds = ref\(new Set\(\['ai_workflows'\]\)\)/)
  assert.match(agentSource, /function serializeShellNavItems\(items = \[\]\)/)
  assert.match(agentSource, /if \(children\.length\) normalized\.children = children/)
  assert.match(slotsSource, /const MAIN_NAV_IDS = \[[^\]]*'ai_workflows'/)
  assert.match(slotsSource, /const expandedNavGroupIds = new Set\(\['ai_workflows'\]\)/)
  assert.match(slotsSource, /function navItemActive\(item, activeId\)/)
  assert.match(slotsSource, /btn\.dataset\.csNavGroup === '1'/)
})

test('AI buyer show workflow submits the Semir MVP task with stepper controls', async () => {
  const workflowSource = await readFile(new URL('../views/BuyerShowWorkflow.vue', import.meta.url), 'utf8')

  assert.match(workflowSource, /const ADAPTER_ID = 'semir-cloud-drive'/)
  assert.match(workflowSource, /const TASK_ID = 'buyer_show_ai_generate'/)
  assert.match(workflowSource, /import \{ AI_IMAGE_MODELS \} from '\.\.\/utils\/aiImageModels\.js'/)
  assert.match(workflowSource, /<nav class="bsv-stepper" role="tablist"/)
  assert.match(workflowSource, /role="tab"/)
  assert.match(workflowSource, /:aria-selected="activeStep === step\.id"/)
  assert.match(workflowSource, /@click="selectStep\(step\)"/)
  assert.match(workflowSource, /function selectStep\(step\)/)
  assert.match(workflowSource, /activeStep\.value = step\.id/)
  assert.match(workflowSource, /const manualStepSelection = ref\(false\)/)
  assert.match(workflowSource, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(workflowSource, /const resultHistoryRuns = ref\(\[\]\)/)
  assert.match(workflowSource, /const selectedResultRunId = ref\(''\)/)
  assert.match(workflowSource, /历史任务队列/)
  assert.match(workflowSource, /class="bsv-run-table"/)
  assert.match(workflowSource, /tabindex="0"/)
  assert.match(workflowSource, /@keydown\.enter\.prevent="selectResultRun\(run\)"/)
  assert.match(workflowSource, /@keydown\.space\.prevent="selectResultRun\(run\)"/)
  assert.match(workflowSource, /resultHistoryRuns\.length/)
  assert.match(workflowSource, /selectedResultRun \? `任务 #\$\{selectedResultRun\.id\}` : '结果详情'/)
  assert.match(workflowSource, /window\.cs\.runTask\(ADAPTER_ID, TASK_ID, buildRunParams\(\), \{\}\)/)
  assert.match(workflowSource, /const DEFAULT_EXPORT_FOLDER = '~\/Downloads\/AI 买家秀全量测试'/)
  assert.match(workflowSource, /const DEFAULT_MODEL_ID = 'gpt-image-4k'/)
  assert.match(workflowSource, /function toPlainJson\(value, fallback\)/)
  assert.match(workflowSource, />生图模型<\/span>/)
  assert.match(workflowSource, /<select v-model="selectedModelId">/)
  assert.match(workflowSource, /'gemini-3.1-flash-image-preview': 'Gemini Flash'/)
  assert.match(workflowSource, /'gemini-3-pro-image-preview': 'Gemini Pro'/)
  assert.match(workflowSource, /execute_mode: executeMode\.value/)
  assert.match(workflowSource, /mode: 'new'/)
  assert.doesNotMatch(workflowSource, /mode: 'current'/)
  assert.match(workflowSource, /flat_cloud_path: flatCloudPath\.value/)
  assert.match(workflowSource, /rows: toPlainJson\(excelPreview\.rows, \[\]\)/)
  assert.match(workflowSource, /headers: toPlainJson\(excelPreview\.headers, \[\]\)/)
  assert.match(workflowSource, /model_id: selectedAiModel\.value\?\.id \|\| DEFAULT_MODEL_ID/)
  assert.match(workflowSource, /model: selectedAiModel\.value\?\.key \|\| 'gpt-image-2'/)
  assert.match(workflowSource, /model_key_tier: selectedAiModel\.value\?\.keyTier \|\| '4k'/)
  assert.match(workflowSource, /image_size: 'source_ratio'/)
  assert.match(workflowSource, /max_generate_jobs: 0/)
  assert.match(workflowSource, /max_model_images_per_row: 500/)
  assert.match(workflowSource, /model_folder_scan_depth: 4/)
  assert.match(workflowSource, /model_folder_scan_max_folders: 500/)
  assert.match(workflowSource, /model_file_info_batch_size: 5/)
  assert.match(workflowSource, /const resumePackageDir = ref\(''\)/)
  assert.match(workflowSource, /<option value="resume">续跑原图包<\/option>/)
  assert.match(workflowSource, /resume_package_dir: isResumeMode\.value \? resumePackageDir\.value : ''/)
  assert.match(workflowSource, /function pickResumePackageDir\(\)/)
  assert.match(workflowSource, /ai_generation_concurrency: 5/)
  assert.match(workflowSource, /ai_result_download_concurrency: 10/)
  assert.match(workflowSource, /title: '找图'[\s\S]*title: 'AI 生图'[\s\S]*title: '结果'/)
  assert.doesNotMatch(workflowSource, /title: '打包'/)
  assert.doesNotMatch(workflowSource, /index: 4/)
  assert.doesNotMatch(workflowSource, /:disabled="step\.disabled"/)
  assert.doesNotMatch(workflowSource, /disabled: !\['done', 'failed'\]/)
  assert.doesNotMatch(workflowSource, /Excel exported[\s\S]*activeStep\.value = 'result'/)
  assert.match(workflowSource, /function applyProgressFromLogs\(logs = \[\]\)/)
  assert.match(workflowSource, /window\.cs\.getData\(ADAPTER_ID, TASK_ID, \{ limit: 0 \}\)/)
  assert.match(workflowSource, /await loadResultHistory\(runId \|\| currentRunId\)/)
  assert.match(workflowSource, /function selectResultRun\(run\)/)
  assert.match(workflowSource, /function parseRunOutputFiles\(run\)/)
  assert.match(workflowSource, /Number\.isNaN\(date\.getTime\(\)\)/)
  assert.match(workflowSource, /AI 生图链接收集进度\\s\+\(\\d\+\)/)
  assert.match(workflowSource, /AI 结果落图进度\\s\+\(\\d\+\)/)
  assert.match(workflowSource, />待生图<\/span>/)
  assert.match(workflowSource, />已拿链接<\/span>/)
  assert.match(workflowSource, />已落图<\/span>/)
  assert.doesNotMatch(workflowSource, />生图尺寸</)
  assert.doesNotMatch(workflowSource, />最多真实生图数</)
  assert.doesNotMatch(workflowSource, />单行最多模拍图</)
  assert.doesNotMatch(workflowSource, />1XM 生图并发</)
  assert.doesNotMatch(workflowSource, />AI 结果落图并发</)
  assert.doesNotMatch(workflowSource, /const imageSize = ref/)
  assert.doesNotMatch(workflowSource, /const maxGenerateJobs = ref/)
  assert.doesNotMatch(workflowSource, /const maxModelImagesPerRow = ref/)
  assert.doesNotMatch(workflowSource, /const generationConcurrency = ref/)
  assert.doesNotMatch(workflowSource, /const resultDownloadConcurrency = ref/)
  assert.match(workflowSource, /usage_record_mode: 'ignore'/)
  assert.doesNotMatch(workflowSource, /\/Users\//)
})
