const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { resolve } = require('node:path')
const test = require('node:test')

const appRoot = resolve(__dirname, '..')

test('worker absolute timeout stops the runtime before reporting failure', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  const timeoutBody = source.match(/timer:\s*setTimeout\(\(\)\s*=>\s*\{([\s\S]*?)\},\s*RUN_ABSOLUTE_TIMEOUT_MS\)/)?.[1] || ''
  assert.match(timeoutBody, /stopRuntime\(\)/)
  assert.match(timeoutBody, /RUN_TIMEOUT/)
})

test('product bridge leases the matching DSH session and honors its approval policy', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-product-bridge/lib/index.js'), 'utf8')
  assert.match(source, /ctx\.on\(['"]tools\/execute['"]/)
  assert.match(source, /postMcpContext\(['"]acquire['"]/) 
  assert.match(source, /postMcpContext\(['"]release['"]/) 
  assert.match(source, /exec\.agent\?\.id/)
  assert.match(source, /finally/)
  assert.match(source, /effectivePolicy\(agent\.session\)/)
  assert.match(source, /policy === ['"]never['"][\s\S]*?outcome: ['"]allowed-once['"]/) 
})

test('agent SSE consumers reconnect from the last persisted event id', () => {
  const productLayer = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentProductLayer.vue'), 'utf8')
  const agentHome = readFileSync(resolve(appRoot, 'src/renderer/views/AgentHome.vue'), 'utf8')
  assert.match(productLayer, /lastEventSeq/)
  assert.match(productLayer, /streamGlobalAgentEvents\(lastEventSeq/)
  assert.match(agentHome, /lastEventSeq/)
  assert.match(agentHome, /streamAgentEvents\(props\.sessionId,\s*lastEventSeq/)
})

test('browser windows are isolated per target and remove closed tabs', () => {
  const main = readFileSync(resolve(appRoot, 'src/agentBrowser.js'), 'utf8')
  const panel = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentBrowserPanel.vue'), 'utf8')
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  const productLayer = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentProductLayer.vue'), 'utf8')
  assert.match(main, /const startingByTarget = new Map\(\)/)
  assert.match(main, /const startingSockets = new Map\(\)/)
  assert.ok(main.indexOf('streams.set(actualTid, st)') < main.indexOf('startingSockets.delete(startKey)', main.indexOf('streams.set(actualTid, st)')))
  assert.match(main, /CDP_COMMAND_TIMEOUT_MS/)
  assert.match(main, /if \(st\.capturing\) return/)
  assert.match(main, /throw new Error\(`绑定的浏览器页面已关闭:/)
  assert.match(main, /targetId:\s*actualTid[\s\S]*?width:[\s\S]*?height:/)
  assert.match(panel, /payload\?\.targetId[\s\S]*?props\.tabId/)
  assert.match(panel, /crawshrimp\.browserWindow\.\$\{String\(props\.tabId/)
  assert.match(webView, /listAgentBrowserTabs\(\)/)
  assert.match(webView, /const closed = browserWindows\.value\.filter/)
  assert.match(webView, /closeBrowserWindow\(win\.tabId\)/)
  assert.match(productLayer, /tool\.approval_resolved/)
  assert.match(productLayer, /run\.interrupted/)
  assert.match(productLayer, /reconcilePendingApprovals/)
  assert.match(productLayer, /\/agent\/approvals\?status=pending/)
  assert.match(productLayer, /pendingIds\.has\(String\(card\.approvalId/)
})

test('DSH attachment bridge sends image content blocks through session prompt', () => {
  const slots = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/lib/client.js'), 'utf8')
  const slotsPackage = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/package.json'), 'utf8'))
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  const worker = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  assert.ok(slotsPackage.dsh.client.inject.includes('@deepseek-ai/dsh-client-runtime'))
  assert.match(slots, /exports\.inject\s*=\s*\[[^\]]*['"]sessions['"]/)
  assert.match(slots, /session\.prompt\([\s\S]*?['"]queue['"]\)/)
  assert.match(slots, /mediaType:[\s\S]*?data:/)
  assert.match(slots, /pendingImagePartsBySession/)
  assert.match(slots, /pendingAttachmentHintsBySession/)
  assert.match(slots, /queueAttachmentHint\(sessionId/)
  assert.match(slots, /localStorage\?\.getItem\?\.\(['"]dsh\.sessions\.current['"]\)/)
  assert.match(slots, /activeRuntimeSessionId\(\)/)
  assert.match(slots, /lastPublishedRuntimeSessionId/)
  assert.match(slots, /current === lastPublishedRuntimeSessionId/)
  assert.match(slots, /document\.documentElement\.dataset\.csAttachCapture/)
  assert.doesNotMatch(slots, /document\.dataset\.csAttachCapture/)
  assert.match(slots, /data\.runtimeSessionId\s*\|\|\s*currentRuntimeSessionId/)
  assert.match(webView, /readAgentImageDataUrl/)
  assert.match(webView, /runtime_session_id:\s*runtimeId/)
  assert.match(webView, /runtimeSessionId:\s*runtimeId/)
  assert.match(worker, /type:\s*['"]image['"]/)
  assert.match(worker, /MODEL_IMAGE_MEDIA_TYPES\.has\(mediaType\)/)
})

test('development bridge never accepts API credentials from URL query', () => {
  const bridge = readFileSync(resolve(appRoot, 'src/renderer/utils/devCsBridge.js'), 'utf8')
  const preload = readFileSync(resolve(appRoot, 'src/preload.js'), 'utf8')
  assert.doesNotMatch(bridge, /TOKEN_QUERY_KEYS/)
  assert.doesNotMatch(bridge, /crawshrimp_token/)
  assert.doesNotMatch(preload, /TOKEN_QUERY_KEYS/)
  assert.doesNotMatch(preload, /crawshrimp_token/)
  assert.match(bridge, /凭证不允许放入 URL query/)
  assert.match(bridge, /只允许访问本机 Crawshrimp API/)
  assert.match(preload, /本地 API 路径必须以单个 \/ 开头/)
  assert.match(bridge, /port < 18765 \|\| port > 18865/)
  assert.match(preload, /port < 18765 \|\| port > 18865/)
})
