const assert = require('node:assert/strict')
const { existsSync, readFileSync } = require('node:fs')
const { resolve } = require('node:path')
const test = require('node:test')

const appRoot = resolve(__dirname, '..')

test('worker absolute timeout stops the runtime before reporting failure', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  const timeoutBody = source.match(/timer:\s*setTimeout\(\(\)\s*=>\s*\{([\s\S]*?)\},\s*RUN_ABSOLUTE_TIMEOUT_MS\)/)?.[1] || ''
  assert.match(timeoutBody, /stopRuntime\(\)/)
  assert.match(timeoutBody, /RUN_TIMEOUT/)
})

test('worker keeps every mutable DSH runtime path under CRAWSHRIMP_DATA', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  assert.match(source, /DSH_HOME:\s*process\.env\.DSH_HOME\s*\|\|\s*`\$\{state\.dataRoot\}\/agent\/dsh-home`/)
  assert.match(source, /CRAWSHRIMP_STORAGE_ROOT:\s*process\.env\.CRAWSHRIMP_STORAGE_ROOT\s*\|\|\s*`\$\{state\.dataRoot\}\/agent\/storages`/)
  assert.match(source, /CRAWSHRIMP_SESSION_ROOT:\s*process\.env\.CRAWSHRIMP_SESSION_ROOT\s*\|\|\s*`\$\{state\.dataRoot\}\/agent\/harness-sessions`/)
})

test('worker compacts image-heavy user message events before FastAPI notifications', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  assert.match(source, /function compactHarnessEvent\(event\)/)
  assert.match(source, /event\.type !== 'user\/message'/)
  assert.match(source, /event:\s*compactHarnessEvent\(event\)/)
  assert.match(source, /function extractEventText\(data\)/)
})

test('staged DSH workspace status probes real read and atomic write access', () => {
  const patcherPath = resolve(appRoot, '../integrations/deepseek-harness/scripts/patch-runtime-dependencies.mjs')
  assert.equal(existsSync(patcherPath), true, 'runtime dependency patcher must be packaged from source')
  const patcher = readFileSync(patcherPath, 'utf8')
  const staging = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/stage-runtime.mjs'), 'utf8')
  assert.match(patcher, /probeWorkspaceDirectoryAccess/)
  assert.match(patcher, /await readdir\(directory\)/)
  assert.match(patcher, /await handle\.sync\(\)/)
  assert.match(patcher, /await rename\(temporary, renamed\)/)
  assert.match(patcher, /await unlink\(renamed\)/)
  assert.match(patcher, /async create\(path, title\)[\s\S]*?await probeWorkspaceDirectoryAccess\(canonical\)/)
  assert.match(patcher, /async status\(\)[\s\S]*?await probeWorkspaceDirectoryAccess\(this\.record\.path\)/)
  assert.match(staging, /patchRuntimeDependencies\(stageRoot\)/)
})

test('staged DSH runtime removes the upstream internal testing welcome notice', () => {
  const patcher = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/patch-runtime-dependencies.mjs'), 'utf8')
  assert.match(patcher, /WELCOME_NOTICE_PATCH_MARKER/)
  assert.match(patcher, /dsh-client-ui-settings-models/)
  assert.match(patcher, /id: "welcome-notice"/)
  assert.match(patcher, /welcome notice onboarding registration/)
})

test('staged DSH runtime bridges DeepSeek image sessions without leaking vision reasoning', () => {
  const patcher = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/patch-runtime-dependencies.mjs'), 'utf8')
  assert.match(patcher, /DEEPSEEK_MULTIMODAL_FALLBACK_PATCH_MARKER/)
  assert.match(patcher, /HOST_APIPROXY_DEEPSEEK_IMAGE_SELECTION_PATCH_MARKER/)
  assert.match(patcher, /SDK_JSONRPC_IMAGE_ADMISSION_PATCH_MARKER/)
  assert.match(patcher, /deepseekPackageEntryPaths/)
  assert.match(patcher, /crawshrimpDeepSeekTextModelCanUseVisionBridge/)
  assert.match(patcher, /deepseek-v4-flash-vision-exp/)
  assert.match(patcher, /crawshrimpBridgeDeepSeekImages/)
  assert.match(patcher, /crawshrimp-deepseek-multimodal-fallback-v2/)
  assert.match(patcher, /OLD_DEEPSEEK_MULTIMODAL_FALLBACK_PATCH_MARKER/)
  assert.match(patcher, /patchPiAiDeepSeekLatestImageTurnBridge/)
  assert.match(patcher, /crawshrimpLatestImageUserMessageIndex/)
  assert.match(patcher, /crawshrimpVisionOptionsForMessage/)
  assert.match(patcher, /crawshrimpTextOnlyOptionsFromVision\(options,\s*visionText,\s*targetIndex\)/)
  assert.match(patcher, /历史图片已省略，避免与本轮图片识别混淆/)
  assert.match(patcher, /请只识别最新一条用户消息里的图片/)
  assert.doesNotMatch(patcher, /请把本轮对话和历史里出现的图片/)
  assert.match(patcher, /completeSimple\(visionModel, visionContext/)
  assert.match(patcher, /DEEPSEEK_MULTIMODAL_AUDIT_PATCH_MARKER/)
  assert.match(patcher, /vision_preflight:\s*true/)
  assert.match(patcher, /deepseek_vision_preflight/)
  assert.match(patcher, /process\.stderr\.write\("crawshrimp\.audit "/)
  assert.match(patcher, /DEEPSEEK_VISION_REASONING_GUARD_PATCH_MARKER/)
  assert.match(patcher, /crawshrimpReasoningEffortForModel/)
  assert.match(patcher, /resolveReasoningLevel\(model, crawshrimpReasoningEffortForModel/)
  assert.match(patcher, /MODEL_DOES_NOT_SUPPORT_IMAGES/)
})

test('desktop dev shell patches DSH runtime dependencies before backend launch', () => {
  const main = readFileSync(resolve(appRoot, 'src/main.js'), 'utf8')
  assert.match(main, /function patchDeepseekHarnessDevRuntime\(harnessRoot\)/)
  assert.match(main, /patch-runtime-dependencies\.mjs/)
  assert.match(main, /ELECTRON_RUN_AS_NODE:\s*'1'/)
  assert.match(main, /patchDeepseekHarnessDevRuntime\(deepseekHarnessRoot\)/)
  assert.match(main, /CRAWSHRIMP_HARNESS_ROOT:\s*deepseekHarnessRoot/)
})

test('product bridge leases the matching DSH session and honors its approval policy', () => {
  const source = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-product-bridge/lib/index.js'), 'utf8')
  assert.match(source, /ctx\.on\(['"]tools\/execute['"]/)
  assert.match(source, /postMcpContext\(['"]acquire['"]/) 
  assert.match(source, /postMcpContext\(['"]release['"]/) 
  assert.match(source, /exec\.agent\?\.id/)
  assert.match(source, /finally/)
  assert.match(source, /effectivePolicy\(agent\.session\)/)
  assert.match(source, /policy === ['"]never['"][\s\S]*?outcome: ['"]allowed-once['"]/) 
})

test('agent SSE consumers reconnect from the last persisted event id', () => {
  const productLayer = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentProductLayer.vue'), 'utf8')
  const agentHome = readFileSync(resolve(appRoot, 'src/renderer/views/AgentHome.vue'), 'utf8')
  assert.match(productLayer, /lastEventSeq/)
  assert.match(productLayer, /streamGlobalAgentEvents\(lastEventSeq/)
  assert.match(agentHome, /lastEventSeq/)
  assert.match(agentHome, /streamAgentEvents\(props\.sessionId,\s*lastEventSeq/)
})

test('agent iframe reloads when runtime generation changes on the same web URL', () => {
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  assert.match(webView, /const runtimeGeneration = ref\(0\)/)
  assert.match(webView, /csRuntimeGeneration/)
  assert.match(webView, /function applyRuntimeSnapshot\(result\)/)
  assert.match(webView, /generation !== runtimeGeneration\.value/)
  assert.match(webView, /const runtimeUrl = applyRuntimeSnapshot\(st\)/)
  assert.match(webView, /webUrl\.value !== runtimeUrl/)
})

test('agent iframe can load backend candidate URL while web verification settles', () => {
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  assert.match(webView, /result\?\.web_url \|\| result\?\.web_candidate_url \|\| ''/)
  assert.match(webView, /Windows packaged builds can serve the first page slowly/)
})

test('core status indicator debounces transient backend probe drops', () => {
  const app = readFileSync(resolve(appRoot, 'src/renderer/App.vue'), 'utf8')
  assert.match(app, /API_STATUS_OFF_STREAK_THRESHOLD = 3/)
  assert.match(app, /apiStatusOffStreak \+= 1/)
  assert.match(app, /status\.value\.api && apiStatusOffStreak < API_STATUS_OFF_STREAK_THRESHOLD/)
  assert.match(app, /window\.cs\.onStatus\(\(\{ key, value \}\) => \{ applyRuntimeStatus\(\{ \[key\]: value \}\) \}\)/)
})

test('browser windows are isolated per target and remove closed tabs', () => {
  const main = readFileSync(resolve(appRoot, 'src/agentBrowser.js'), 'utf8')
  const app = readFileSync(resolve(appRoot, 'src/renderer/App.vue'), 'utf8')
  const panel = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentBrowserPanel.vue'), 'utf8')
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  const productLayer = readFileSync(resolve(appRoot, 'src/renderer/components/agent/AgentProductLayer.vue'), 'utf8')
  const showBrowserWindows = webView.split('function showBrowserWindows()', 2)[1]?.split('\nfunction hideBrowserWindow', 1)[0] || ''
  const appTabPicker = app.split('function tabsForActiveBrowserWindow(payload)', 2)[1]?.split('\nfunction onBrowserOpenTabs', 1)[0] || ''
  const webTabPicker = webView.split('function tabsForActiveBrowserWindow(payload)', 2)[1]?.split('\nfunction syncBrowserTabs', 1)[0] || ''
  assert.match(main, /const startingByTarget = new Map\(\)/)
  assert.match(main, /const startingSockets = new Map\(\)/)
  assert.ok(main.indexOf('streams.set(actualTid, st)') < main.indexOf('startingSockets.delete(startKey)', main.indexOf('streams.set(actualTid, st)')))
  assert.match(main, /CDP_COMMAND_TIMEOUT_MS/)
  assert.match(main, /if \(st\.capturing\) return/)
  assert.match(main, /throw new Error\(`绑定的浏览器页面已关闭:/)
  assert.match(main, /targetId:\s*actualTid[\s\S]*?width:[\s\S]*?height:/)
  assert.match(panel, /payload\?\.targetId[\s\S]*?props\.tabId/)
  assert.match(panel, /crawshrimp\.browserWindow\.v2\.\$\{String\(props\.tabId/)
  assert.match(panel, /@pointerdown\.left="onDragStart"/)
  assert.match(panel, /:disabled="isDocked"/)
  assert.match(panel, /layout-change/)
  assert.match(panel, /data-tooltip/)
  assert.match(panel, /layoutActionLabel/)
  assert.match(panel, /IconLayoutSidebarRight/)
  assert.match(panel, /IconExternalLink/)
  assert.doesNotMatch(panel, /IconWindow/)
  assert.match(panel, /if \(isDocked\.value\) return/)
  assert.match(panel, /safelySetPointerCapture/)
  assert.match(panel, /safelyReleasePointerCapture/)
  assert.match(panel, /stopInteractions/)
  assert.match(panel, /watch\(isDocked/)
  assert.match(panel, /window\.addEventListener\('pointerdown', onNextPointerDown, \{ capture: true \}\)/)
  assert.match(panel, /window\.addEventListener\('blur', onFinish, \{ once: true \}\)/)
  assert.match(panel, /requestAnimationFrame/)
  assert.match(panel, /translate3d\(\$\{win\.x\}px, \$\{win\.y\}px, 0\)/)
  assert.match(panel, /DEFAULT_FLOAT_W = 520/)
  assert.match(panel, /defaultY = 54 \+ off/)
  assert.match(panel, /\.layout-btn::after[\s\S]*?content: attr\(data-tooltip\)/)
  assert.match(panel, /IconArrowsMaximize/)
  assert.match(panel, /IconMinus/)
  assert.match(panel, /IconX/)
  assert.match(webView, /listAgentBrowserTabs\(\)/)
  assert.match(webView, /visibleBrowserWindows/)
  assert.match(webView, /const browserLayout = ref\(loadBrowserLayoutPreference\(\)\)/)
  assert.match(webView, /BROWSER_LAYOUT_STORAGE_KEY = 'crawshrimp\.browserLayout\.v2'/)
  assert.match(webView, /hasDockedBrowserWindows/)
  assert.match(webView, /web-browser-panel/)
  assert.match(webView, /v-show="hasDockedBrowserWindows"/)
  assert.match(webView, /:key="win\.tabId"/)
  assert.match(webView, /:layout="browserLayout"/)
  assert.doesNotMatch(webView, /floatingBrowserWindows/)
  assert.doesNotMatch(webView, /`docked-\$\{win\.tabId\}`/)
  assert.doesNotMatch(webView, /`floating-\$\{win\.tabId\}`/)
  assert.match(webView, /width:\s*min\(680px, max\(360px, 40vw\), 46%\)/)
  assert.match(webView, /\.browser-docked \.web-frame-wrap[\s\S]*?min-width:\s*min\(420px, 54%\)/)
  assert.match(webView, /setBrowserLayout/)
  assert.match(webView, /return value === 'docked' \? 'docked' : 'floating'/)
  assert.match(webView, /toggleBrowserWindows/)
  assert.match(webView, /showBrowserWindows/)
  assert.match(webView, /tabsForActiveBrowserWindow/)
  assert.match(webView, /hideBrowserWindow\(win\.tabId\)/)
  assert.match(webView, /:disabled="!canToggleBrowserWindows"/)
  assert.match(webView, /const closed = browserWindows\.value\.filter/)
  assert.match(webView, /removeBrowserWindow\(win\.tabId\)/)
  assert.doesNotMatch(webView, /@click="browserOpen = !browserOpen"/)
  assert.match(showBrowserWindows, /sessionBrowserTabs\.value\.length/)
  assert.doesNotMatch(showBrowserWindows, /listAgentBrowserTabs/)
  assert.match(appTabPicker, /activeTabId/)
  assert.match(appTabPicker, /tabs\.find/)
  assert.match(appTabPicker, /return \{ tabs: \[active\], activeTabId \}/)
  assert.match(appTabPicker, /return \{ tabs: \[\], activeTabId \}/)
  assert.doesNotMatch(appTabPicker, /return \{ tabs, activeTabId/)
  assert.match(webTabPicker, /activeTabId/)
  assert.match(webTabPicker, /tabs\.find/)
  assert.match(webTabPicker, /return \[active\]/)
  assert.match(webTabPicker, /return \[\]/)
  assert.doesNotMatch(webTabPicker, /return tabs\s*(?:;|\n|\})/)
  assert.match(productLayer, /tool\.approval_resolved/)
  assert.match(productLayer, /run\.interrupted/)
  assert.match(productLayer, /reconcilePendingApprovals/)
  assert.match(productLayer, /\/agent\/approvals\?status=pending/)
  assert.match(productLayer, /pendingIds\.has\(String\(card\.approvalId/)
})

test('DSH attachment bridge leaves images to the native composer rail', () => {
  const slots = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/lib/client.js'), 'utf8')
  const slotsPackage = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/package.json'), 'utf8'))
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  const worker = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/worker/worker.mjs'), 'utf8')
  assert.ok(slotsPackage.dsh.client.inject.includes('@deepseek-ai/dsh-client-runtime'))
  assert.match(slots, /exports\.inject\s*=\s*\[[^\]]*['"]sessions['"]/)
  assert.match(slots, /function isImageFile\(file\)/)
  assert.match(slots, /function nonImageFiles\(files\)/)
  assert.match(slots, /filter\(\(file\) => file && !isImageFile\(file\)\)/)
  assert.doesNotMatch(slots, /pendingImagePartsBySession/)
  assert.doesNotMatch(slots, /submitPendingImages/)
  assert.doesNotMatch(slots, /session\.prompt\([\s\S]*?pendingImage/)
  assert.doesNotMatch(slots, /imagePart/)
  assert.match(slots, /pendingAttachmentHintsBySession/)
  assert.match(slots, /queueAttachmentHint\(sessionId/)
  assert.match(slots, /localStorage\?\.getItem\?\.\(['"]dsh\.sessions\.current['"]\)/)
  assert.match(slots, /activeRuntimeSessionId\(\)/)
  assert.match(slots, /lastPublishedRuntimeSessionId/)
  assert.match(slots, /current === lastPublishedRuntimeSessionId/)
  assert.match(slots, /function updateNavButton\(btn,\s*item,\s*activeId\)/)
  assert.match(slots, /function findNavButton\(host,\s*id\)/)
  assert.match(slots, /function updateNavToggle\(toggle,\s*host,\s*items,\s*activeId,\s*collapsible\)/)
  assert.match(slots, /btn\.dataset\.csNavItemId/)
  assert.match(slots, /host\.insertBefore\(btn,\s*toggle \|\| null\)/)
  assert.doesNotMatch(slots, /host\.replaceChildren\(\)/)
  assert.doesNotMatch(slots, /cs-nav-in/)
  assert.match(slots, /document\.documentElement\.dataset\.csAttachCapture/)
  assert.doesNotMatch(slots, /document\.dataset\.csAttachCapture/)
  assert.match(slots, /data\.runtimeSessionId\s*\|\|\s*currentRuntimeSessionId/)
  assert.match(slots, /const UPLOAD_BUTTON_TOOLTIP = ['"]上传附件['"]/)
  assert.match(slots, /function setComposerButtonTooltip\(button,\s*tooltip,\s*ariaLabel\)/)
  assert.match(slots, /button\.dataset\.csTooltip = tooltip/)
  assert.match(slots, /delete button\.dataset\.csTooltip/)
  assert.match(slots, /color:\s*#f7f7fa;/)
  assert.doesNotMatch(slots, /var\(--dsw-alias-label-primary-inverted/)
  assert.match(slots, /addBtn\.removeAttribute\(['"]aria-haspopup['"]\)/)
  assert.match(slots, /addBtn\.removeAttribute\(['"]aria-expanded['"]\)/)
  assert.match(slots, /function installComposerTooltipShield\(\)/)
  assert.match(slots, /function composerTooltipButtonFromEvent\(event\)/)
  assert.match(slots, /function isComposerTooltipButton\(target\)/)
  assert.match(slots, /document\.documentElement\.dataset\.csComposerTooltipShield = ['"]1['"]/)
  assert.match(slots, /\[data-cs-composer-tooltip-shield="1"\] \[role="tooltip"\]/)
  assert.match(slots, /\[role="tooltip"\]\[data-cs-suppressed-tooltip="1"\]/)
  assert.match(slots, /function suppressNativeCommandTooltips\(\)/)
  assert.match(slots, /function installNativeCommandTooltipSuppressor\(\)/)
  assert.match(slots, /String\(tooltip\.textContent \|\| ''\)\.trim\(\) !== COMMAND_BUTTON_LABEL/)
  assert.match(slots, /target\.closest\('\.uV2eYG_add\[data-cs-upload-button="1"\], \.uV2eYG_add\.cs-cmd-at-btn'\)/)
  assert.match(slots, /at\.dataset\.csCommandButton = ['"]1['"]/)
  assert.match(slots, /setComposerButtonTooltip\(at,\s*COMMAND_BUTTON_LABEL,\s*COMMAND_BUTTON_LABEL\)/)
  assert.doesNotMatch(slots, /setComposerButtonTooltip\(at,\s*null,\s*COMMAND_BUTTON_LABEL\)/)
  assert.match(slots, /if \(at\.className !== wantedClass\) at\.className = wantedClass/)
  assert.match(slots, /if \(at\.dataset\.csCommandButton !== ['"]1['"]\) at\.dataset\.csCommandButton = ['"]1['"]/)
  assert.match(slots, /if \(at\.getAttribute\(['"]aria-haspopup['"]\) !== ['"]listbox['"]\)/)
  assert.match(slots, /if \(!glyph \|\| glyph\.textContent !== ['"]@['"]\)/)
  assert.doesNotMatch(slots, /at\.innerHTML = ['"]['"]/)
  assert.match(slots, /let composerButtonMountQueued = false/)
  assert.match(slots, /function scheduleComposerButtonMount\(\)/)
  assert.match(slots, /requestAnimationFrame\(run\)/)
  assert.match(slots, /let lastRailMetricsSignature = ['"]['"]/)
  assert.match(slots, /function scheduleRailMetricsPush\(force = false\)/)
  assert.match(slots, /function installRailResizeObserver\(\)/)
  assert.match(slots, /signature === lastRailMetricsSignature/)
  assert.match(slots, /function mutationsTouchShellMountPoints\(mutations\)/)
  assert.match(slots, /if \(!mutationsTouchShellMountPoints\(mutations\)\) return/)
  assert.match(slots, /scheduleComposerButtonMount\(\)[\s\S]*?installRailResizeObserver\(\)[\s\S]*?scheduleRailMetricsPush\(\)/)
  assert.match(slots, /observer\.observe\(document\.documentElement,\s*\{\s*childList:\s*true,\s*subtree:\s*true\s*\}\)/)
  assert.doesNotMatch(slots, /observer\.observe\(document\.documentElement,\s*\{[^\}]*attributes:\s*true/)
  assert.doesNotMatch(slots, /attributeFilter:\s*\[['"]class['"],\s*['"]style['"]\]/)
  assert.match(webView, /function isImageLikeFile\(file\)/)
  assert.match(webView, /if \(isImageLikeFile\(file\)\) return/)
  assert.match(webView, /if \(isImageLikeFile\(file\)\) continue/)
  assert.doesNotMatch(webView, /attachmentImagePart/)
  assert.doesNotMatch(webView, /readAgentImageDataUrl/)
  assert.match(webView, /runtime_session_id:\s*runtimeId/)
  assert.match(webView, /runtimeSessionId:\s*runtimeId/)
  assert.match(worker, /type:\s*['"]image['"]/)
  assert.match(worker, /MODEL_IMAGE_MEDIA_TYPES\.has\(mediaType\)/)
})

test('DSH attachment bridge resets and retitles the native file-drop overlay', () => {
  const slots = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/lib/client.js'), 'utf8')
  const dropHandler = slots.split('function handleDropAttachments(event)', 2)[1]?.split('\n    const DROP_TITLE_ZH', 1)[0] || ''

  assert.match(slots, /function hasFileTransfer\(event\)/)
  assert.doesNotMatch(dropHandler, /inComposer\(event\.target\)/)
  assert.match(slots, /function resetNativeDropOverlay\(\)/)
  assert.match(slots, /event = new Event\(['"]dragend['"]\)/)
  assert.match(slots, /document\.createEvent\(['"]Event['"]\)/)
  assert.match(slots, /window\.dispatchEvent\(event\)/)
  assert.match(slots, /function installNativeDropOverlayFixups\(\)/)
  assert.match(slots, /document\.addEventListener\(['"]drop['"],\s*\(event\) => \{[\s\S]*?hasFileTransfer\(event\)[\s\S]*?resetNativeDropOverlay\(\)[\s\S]*?\},\s*true\)/)
  assert.match(slots, /try \{[\s\S]*?postAttachmentFiles\(attachments\)[\s\S]*?\} finally \{[\s\S]*?resetNativeDropOverlay\(\)[\s\S]*?\}/)
  assert.match(slots, /const DROP_TITLE_ZH = ['"]图片\/文件拖动到此处即可添加['"]/)
  assert.match(slots, /const DROP_TITLE_EN = ['"]Drag images or files here to add them['"]/)
  assert.match(slots, /const FILE_LIMIT_ZH = ['"]文件最大 200MB['"]/)
  assert.match(slots, /Images: up to \$1, \$2 each; \$\{FILE_LIMIT_EN\}/)
  assert.match(slots, /mutationTouchesDropOverlay/)
  assert.match(slots, /installNativeDropOverlayFixups\(\)[\s\S]*?if \(document\.documentElement\.dataset\.csAttachCapture === ['"]1['"]\) return/)
})

test('DSH Crawshrimp brand slots replace the official DeepSeek Harness wordmark', () => {
  const slots = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/lib/client.js'), 'utf8')
  const slotsPackage = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/package.json'), 'utf8'))
  const webCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/web-cordis.yml'), 'utf8')
  const brandOfficialBlock = webCordis.split('- id: ui-brand-official', 2)[1]?.split('\n- id:', 1)[0] || ''

  assert.ok(slotsPackage.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-sidebar'))
  assert.ok(slotsPackage.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-conversation'))
  assert.match(slots, /exports\.inject\s*=\s*\[[^\]]*['"]slots['"]/)
  assert.match(slots, /CrawshrimpBrandMark/)
  assert.match(slots, /CrawshrimpBrandName/)
  assert.match(slots, /normalizeDocumentTitle/)
  assert.match(slots, /setInterval\(normalizeDocumentTitle,\s*1000\)/)
  assert.match(slots, /ctx\.slots\.inject\(['"]sidebar\.brand\.mark['"]/)
  assert.match(slots, /ctx\.slots\.inject\(['"]sidebar\.brand\.name['"]/)
  assert.match(slots, /ctx\.slots\.inject\(['"]conversation\.hero\.brand\.mark['"]/)
  assert.match(slots, /ctx\.slots\.register\(\{\s*name:\s*['"]sidebar\.brand\.mark['"]/)
  assert.match(slots, /ctx\.slots\.register\(\{\s*name:\s*['"]sidebar\.brand\.name['"]/)
  assert.match(slots, /ctx\.slots\.register\(\{\s*name:\s*['"]conversation\.hero\.brand\.mark['"]/)
  assert.match(slots, /抓虾智能体/)
  assert.doesNotMatch(slots, /hHd-Xa_brand::after/)
  assert.doesNotMatch(slots, /抓虾 Harness 智能体/)
  assert.match(brandOfficialBlock, /name:\s*'@deepseek-ai\/dsh-client-ui-brand-official'/)
  assert.match(brandOfficialBlock, /disabled:\s*true/)
})

test('agent persona introduces itself as Crawshrimp agent', () => {
  const webCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/web-cordis.yml'), 'utf8')
  const genWebCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/gen-web-cordis.py'), 'utf8')
  const runtimeCordisSource = readFileSync(resolve(appRoot, '../core/agent/cordis_config.py'), 'utf8')
  const promptBlock = webCordis.split('- id: system-prompt', 2)[1]?.split('\n- id:', 1)[0] || ''

  for (const source of [promptBlock, genWebCordis, runtimeCordisSource]) {
    assert.match(source, /你是抓虾智能体/)
    assert.match(source, /只有当用户明确询问身份[\s\S]*首句回答[\s\S]*我是抓虾智能体/)
    assert.match(source, /普通寒暄[\s\S]*不要主动自我介绍[\s\S]*不要写[\s\S]*我是抓虾智能体/)
    assert.match(source, /能力咨询[\s\S]*不要以身份开头/)
    assert.match(source, /用户说[\s\S]*你好[\s\S]*需要我帮你处理什么/)
    assert.doesNotMatch(source, /首句必须明确回答/)
    assert.doesNotMatch(source, /你是抓虾桌面应用中的操作智能体/)
  }
})

test('DSH rc.8 dependency graph keeps launcher and runtime on one cmdline version', () => {
  const harnessPackage = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/package.json'), 'utf8'))
  const launcherPackage = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-launcher/package.json'), 'utf8'))
  const lock = JSON.parse(readFileSync(resolve(appRoot, '../integrations/deepseek-harness/package-lock.json'), 'utf8'))
  const expected = '0.1.0-rc.8'
  const requiredWebPackages = [
    '@deepseek-ai/dsh-client-ui-attachment',
    '@deepseek-ai/dsh-client-ui-brand-official',
    '@deepseek-ai/dsh-client-ui-directory-picker-browse',
    '@deepseek-ai/dsh-client-ui-reference',
    '@deepseek-ai/dsh-client-ui-renderer',
    '@deepseek-ai/dsh-file-reference-local',
    '@deepseek-ai/dsh-host-directory-picker-browse',
    '@deepseek-ai/dsh-session-reference',
  ]

  for (const [name, version] of Object.entries(harnessPackage.dependencies)) {
    if (name.startsWith('@deepseek-ai/')) assert.equal(version, expected, `${name} must stay on ${expected}`)
  }
  for (const name of requiredWebPackages) {
    assert.equal(harnessPackage.dependencies[name], expected, `${name} must be a direct runtime dependency`)
    assert.equal(lock.packages[''].dependencies[name], expected, `${name} must be pinned in package-lock root`)
  }
  assert.equal(launcherPackage.dependencies['@deepseek-ai/dsh-cmdline'], expected)
  assert.equal(lock.packages['crawshrimp-launcher'].dependencies['@deepseek-ai/dsh-cmdline'], expected)

  const cmdlineEntries = Object.entries(lock.packages)
    .filter(([key]) => key.includes('@deepseek-ai/dsh-cmdline'))
    .map(([key, value]) => [key, value.version])
  assert.deepEqual(cmdlineEntries, [['node_modules/@deepseek-ai/dsh-cmdline', expected]])
})

test('DSH workspace directory picker uses Crawshrimp shell native bridge in Windows builds', () => {
  const webCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/web-cordis.yml'), 'utf8')
  const genWebCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/gen-web-cordis.py'), 'utf8')
  const stageRuntime = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/stage-runtime.mjs'), 'utf8')
  const webView = readFileSync(resolve(appRoot, 'src/renderer/views/AgentWebView.vue'), 'utf8')
  const slots = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/crawshrimp-slots/lib/client.js'), 'utf8')
  const main = readFileSync(resolve(appRoot, 'src/main.js'), 'utf8')
  const autoBlock = webCordis.split('- id: directory-picker', 2)[1]?.split('\n- id:', 1)[0] || ''
  const winBrowseBlock = webCordis.split('- id: directory-picker-win-browse', 2)[1]?.split('\n- id:', 1)[0] || ''
  const winBrowseUiBlock = webCordis.split('- id: ui-directory-picker-win-browse', 2)[1]?.split('\n- id:', 1)[0] || ''
  const browseHandler = main.split("secureHandle('browse-file'", 2)[1]?.split("\nsecureHandle('select-bala-workspace'", 1)[0] || ''

  assert.match(autoBlock, /name:\s*'@deepseek-ai\/dsh-host-directory-picker-auto'/)
  assert.match(autoBlock, /disabled:\s*!!js process\.platform === 'win32' \|\| \['browse', 'shell'\]\.includes\(process\.env\.CRAWSHRIMP_DIRECTORY_PICKER_MODE \|\| ''\)/)
  assert.match(winBrowseBlock, /name:\s*'@deepseek-ai\/dsh-host-directory-picker-browse'/)
  assert.match(winBrowseBlock, /disabled:\s*!!js process\.platform !== 'win32' && !\['browse', 'shell'\]\.includes\(process\.env\.CRAWSHRIMP_DIRECTORY_PICKER_MODE \|\| ''\)/)
  assert.match(winBrowseUiBlock, /name:\s*'@deepseek-ai\/dsh-client-ui-directory-picker-browse'/)
  assert.match(winBrowseUiBlock, /disabled:\s*!!js process\.env\.CRAWSHRIMP_DIRECTORY_PICKER_MODE !== 'browse'/)
  assert.match(genWebCordis, /directory-picker-win-browse/)
  assert.match(genWebCordis, /ui-directory-picker-win-browse/)
  assert.match(genWebCordis, /process\.platform === 'win32'/)
  assert.match(stageRuntime, /cordisFile:\s*'web-cordis\.yml'/)
  assert.match(stageRuntime, /CRAWSHRIMP_DIRECTORY_PICKER_MODE:\s*'shell'/)
  assert.match(stageRuntime, /browse picker client entry unexpectedly active/)
  assert.match(stageRuntime, /native picker client entry unexpectedly active/)
  assert.match(stageRuntime, /Crawshrimp slots active, upstream picker absent/)
  assert.match(stageRuntime, /CRAWSHRIMP_STAGE_BOOT_CHECK:\s*'1'/)
  assert.match(webCordis, /failOnStartupError:\s*!!js process\.env\.CRAWSHRIMP_STAGE_BOOT_CHECK !== '1'/)
  assert.match(webView, /url\.searchParams\.set\('csDirectoryPicker', 'shell'\)/)
  assert.match(webView, /function shouldUseShellDirectoryPicker\(\)/)
  assert.match(webView, /data\.__crawshrimp === 'workspace-directory-pick'/)
  assert.match(webView, /window\.cs\.browseFile\(\{[\s\S]*directory:\s*true,[\s\S]*createDirectory:\s*true/)
  assert.match(slots, /function CrawshrimpShellDirectoryFlow\(props\)/)
  assert.match(slots, /conversation\.hero\.workspace\.directoryFlow/)
  assert.match(slots, /sidebar\.workspaces\.directoryFlow/)
  assert.match(slots, /workspace-directory-pick/)
  assert.match(slots, /workspace-directory-picked/)
  assert.match(browseHandler, /if \(opts\.directory && opts\.createDirectory\) props\.push\('createDirectory'\)/)
})

test('DSH web cordis registers Crawshrimp DeepSeek provider without exposing the native route', () => {
  const webCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/web-cordis.yml'), 'utf8')
  const launcherBlock = webCordis.split('- id: launcher', 2)[1].split('\n- id:', 1)[0]
  const webRuntimeBlock = webCordis.split('- id: web-runtime', 2)[1].split('\n- id:', 1)[0]
  const defaultBlock = webCordis.split('- id: agent-default-model', 2)[1].split('\n- id:', 1)[0]
  const attachmentBlock = webCordis.split('- id: attachment-local', 2)[1].split('\n- id:', 1)[0]
  const piAiBlock = webCordis.split('- id: llm-pi-ai', 2)[1].split('\n- id:', 1)[0]
  const nativeBlock = webCordis.split('- id: llm-deepseek', 2)[1].split('\n- id:', 1)[0]
  const genWebCordis = readFileSync(resolve(appRoot, '../integrations/deepseek-harness/scripts/gen-web-cordis.py'), 'utf8')
  const activeWebRows = [
    ['session-reference', '@deepseek-ai/dsh-session-reference'],
    ['file-reference-local', '@deepseek-ai/dsh-file-reference-local'],
    ['ui-renderer', '@deepseek-ai/dsh-client-ui-renderer'],
    ['ui-attachment', '@deepseek-ai/dsh-client-ui-attachment'],
    ['ui-reference', '@deepseek-ai/dsh-client-ui-reference'],
  ]
  const brandOfficialBlock = webCordis.split('- id: ui-brand-official', 2)[1]?.split('\n- id:', 1)[0] || ''

  assert.match(launcherBlock, /--no-open/)
  assert.match(webRuntimeBlock, /openBrowser:\s*!!js ctx\.webStartup\.openBrowser/)
  assert.match(defaultBlock, /provider:\s*!!js process\.env\.CRAWSHRIMP_AGENT_PROVIDER \?\? 'crawshrimp-deepseek-official'/)
  assert.match(defaultBlock, /model:\s*!!js process\.env\.CRAWSHRIMP_AGENT_MODEL \?\? 'deepseek-v4-flash'/)
  assert.match(attachmentBlock, /maxImageDimension:\s*4096/)
  assert.match(attachmentBlock, /maxImageBytes:\s*16777216/)
  assert.match(genWebCordis, /maxImageDimension:\s*4096/)
  assert.match(genWebCordis, /maxImageBytes:\s*16777216/)
  assert.match(piAiBlock, /providers\['crawshrimp-deepseek-official'\]/)
  assert.match(piAiBlock, /apiKeyEnv:\s*'CRAWSHRIMP_DEEPSEEK_API_KEY'/)
  assert.match(piAiBlock, /baseURL:[\s\S]*CRAWSHRIMP_DEEPSEEK_BASE_URL[\s\S]*https:\/\/api\.deepseek\.com/)
  assert.match(piAiBlock, /id:\s*'deepseek-v4-flash'/)
  assert.match(piAiBlock, /reasoning:\s*'high'/)
  assert.match(piAiBlock, /reasoningEfforts:\s*\{\s*off:\s*null,\s*low:\s*'low',\s*high:\s*'high',\s*max:\s*'max'\s*\}/)
  assert.match(piAiBlock, /id:\s*'deepseek-v4-flash-vision-exp'[\s\S]*input:\s*\['text',\s*'image'\]/)
  assert.doesNotMatch(piAiBlock.match(/id:\s*'deepseek-v4-flash-vision-exp'[^\n]+/)?.[0] || '', /reasoningEfforts|reasoning:\s*'high'/)
  assert.match(nativeBlock, /disabled:\s*true/)

  for (const [id, packageName] of activeWebRows) {
    const block = webCordis.split(`- id: ${id}`, 2)[1]?.split('\n- id:', 1)[0] || ''
    assert.match(block, new RegExp(`name:\\s*'${packageName.replaceAll('/', '\\/')}'`))
    assert.doesNotMatch(block, /disabled:\s*true/)
  }
  assert.match(brandOfficialBlock, /name:\s*'@deepseek-ai\/dsh-client-ui-brand-official'/)
  assert.match(brandOfficialBlock, /disabled:\s*true/)
})

test('development bridge never accepts API credentials from URL query', () => {
  const bridge = readFileSync(resolve(appRoot, 'src/renderer/utils/devCsBridge.js'), 'utf8')
  const preload = readFileSync(resolve(appRoot, 'src/preload.js'), 'utf8')
  assert.doesNotMatch(bridge, /TOKEN_QUERY_KEYS/)
  assert.doesNotMatch(bridge, /crawshrimp_token/)
  assert.doesNotMatch(preload, /TOKEN_QUERY_KEYS/)
  assert.doesNotMatch(preload, /crawshrimp_token/)
  assert.match(bridge, /凭证不允许放入 URL query/)
  assert.match(bridge, /只允许访问本机 Crawshrimp API/)
  assert.match(preload, /本地 API 路径必须以单个 \/ 开头/)
  assert.match(bridge, /port < 18765 \|\| port > 18865/)
  assert.match(preload, /port < 18765 \|\| port > 18865/)
})
